import type {
  Dish,
  DishFlavor,
  DishIngredient,
  Flavor,
  Ingredient,
  IngredientCategory,
} from './types';
import { getPlaceholderImage } from './placeholder-images';

export const allFlavors: Flavor[] = [
  { id: 1, name: 'Chua' },
  { id: 2, name: 'Cay' },
  { id: 3, name: 'Mặn' },
  { id: 4, name: 'Ngọt' },
  { id: 5, name: 'Thanh đạm' },
  { id: 6, name: 'Béo ngậy' },
  { id: 7, name: 'Thơm lừng' },
  { id: 8, name: 'Chua cay' },
  { id: 9, name: 'Ngọt mặn' },
  { id: 10, name: 'Đắng' },
  { id: 11, name: 'Bùi' },
  { id: 12, name: 'Giòn' },
  { id: 13, name: 'Thơm dừa' },
  { id: 14, name: 'Thơm tỏi' },
];

export const allIngredientCategories: IngredientCategory[] = [
  { id: 1, name: 'Thịt' },
  { id: 2, name: 'Rau củ' },
  { id: 3, name: 'Hải sản' },
  { id: 4, name: 'Tinh bột' },
  { id: 5, name: 'Gia vị' },
  { id: 6, name: 'Trứng/Sữa' },
  { id: 7, name: 'Đậu/Nấm' },
  { id: 8, name: 'Trái cây' },
];

export const allIngredients: Ingredient[] = [
  { id: 1, name: 'Thịt bò', categoryId: 1 },
  { id: 2, name: 'Thịt gà', categoryId: 1 },
  { id: 3, name: 'Tôm', categoryId: 3 },
  { id: 4, name: 'Cà chua', categoryId: 2 },
  { id: 5, name: 'Bún', categoryId: 4 },
  { id: 6, name: 'Phở (Bánh phở)', categoryId: 4 },
  { id: 7, name: 'Nước mắm', categoryId: 5 },
  { id: 8, name: 'Ớt', categoryId: 2 },
  { id: 9, name: 'Sả', categoryId: 2 },
  { id: 10, name: 'Gạo', categoryId: 4 },
  { id: 11, name: 'Cá lóc', categoryId: 3 },
  { id: 12, name: 'Sườn heo', categoryId: 1 },
  { id: 13, name: 'Chả cá (thịt cá)', categoryId: 3 },
  { id: 14, name: 'Đậu phụ', categoryId: 7 },
  { id: 15, name: 'Ốc', categoryId: 3 },
  { id: 16, name: 'Rau sống', categoryId: 2 },
  { id: 17, name: 'Cà rốt', categoryId: 2 },
  { id: 18, name: 'Trứng gà', categoryId: 6 },
  { id: 19, name: 'Dừa (cùi dừa)', categoryId: 8 },
  { id: 20, name: 'Khoai tây', categoryId: 2 },
  { id: 21, name: 'Nấm hương', categoryId: 7 },
  { id: 22, name: 'Bí đao', categoryId: 2 },
  { id: 23, name: 'Hành tây', categoryId: 2 },
  { id: 24, name: 'Thịt ba chỉ', categoryId: 1 },
  { id: 25, name: 'Mực', categoryId: 3 },
  { id: 26, name: 'Bông cải xanh', categoryId: 2 },
  { id: 27, name: 'Hạt điều', categoryId: 7 },
  { id: 28, name: 'Cải thảo', categoryId: 2 },
  { id: 29, name: 'Cá diêu hồng', categoryId: 3 },
  { id: 30, name: 'Thịt vịt', categoryId: 1 },
  { id: 31, name: 'Gừng', categoryId: 2 },
  { id: 32, name: 'Sấu', categoryId: 8 },
  { id: 33, name: 'Nghêu', categoryId: 3 },
  { id: 34, name: 'Mì tôm', categoryId: 4 },
  { id: 35, name: 'Xoài', categoryId: 8 },
  { id: 36, name: 'Bơ', categoryId: 8 },
  { id: 37, name: 'Sữa tươi', categoryId: 6 },
  { id: 38, name: 'Yến mạch', categoryId: 4 },
  { id: 39, name: 'Bắp cải', categoryId: 2 },
  { id: 40, name: 'Tỏi', categoryId: 2 },
  { id: 41, name: 'Húng quế', categoryId: 2 },
  { id: 42, name: 'Lá é', categoryId: 2 },
  { id: 43, name: 'Bưởi', categoryId: 8 },
  { id: 44, name: 'Đậu phộng (lạc)', categoryId: 7 },
  { id: 45, name: 'Nước cốt dừa', categoryId: 5 },
  { id: 46, name: 'Bánh mì', categoryId: 4 },
  { id: 47, name: 'Tương ớt', categoryId: 5 },
  { id: 48, name: 'Dầu hào', categoryId: 5 },
  { id: 49, name: 'Gạo nếp', categoryId: 4 },
  { id: 50, name: 'Lá lốt', categoryId: 2 },
  { id: 51, name: 'Chuối xanh', categoryId: 8 },
  { id: 52, name: 'Mắm tôm', categoryId: 5 },
  { id: 53, name: 'Dứa', categoryId: 8 },
  { id: 54, name: 'Cà tím', categoryId: 2 },
  { id: 55, name: 'Lá chanh', categoryId: 2 },
  { id: 56, name: 'Nấm rơm', categoryId: 7 },
  { id: 57, name: 'Khoai môn', categoryId: 2 },
  { id: 58, name: 'Hành lá', categoryId: 2 },
  { id: 59, name: 'Hạt tiêu', categoryId: 5 },
  { id: 60, name: 'Măng', categoryId: 2 },
  { id: 61, name: 'Bánh đa', categoryId: 4 },
  { id: 62, name: 'Cua đồng', categoryId: 3 },
  { id: 63, name: 'Giò chả', categoryId: 1 },
  { id: 64, name: 'Thính', categoryId: 4 },
  { id: 65, name: 'Tai heo', categoryId: 1 },
  { id: 66, name: 'Lươn', categoryId: 3 },
  { id: 67, name: 'Bột năng', categoryId: 5 },
  { id: 68, name: 'Gấc', categoryId: 8 },
  { id: 69, name: 'Cá chép', categoryId: 3 },
  { id: 70, name: 'Thịt ngan', categoryId: 1 },
  { id: 71, name: 'Bánh tráng', categoryId: 4 },
  { id: 72, name: 'Khô bò', categoryId: 1 },
  { id: 73, name: 'Thanh long', categoryId: 8 },
  { id: 74, name: 'Dưa hấu', categoryId: 8 },
  { id: 75, name: 'Nho', categoryId: 8 },
  { id: 76, name: 'Dâu tây', categoryId: 8 },
  { id: 77, name: 'Cam', categoryId: 8 },
  { id: 78, name: 'Chanh', categoryId: 8 },
  { id: 79, name: 'Kiwi', categoryId: 8 },
  { id: 80, name: 'Đào', categoryId: 8 },
  { id: 81, name: 'Bơ sáp', categoryId: 8 },
  { id: 82, name: 'Vải', categoryId: 8 },
  { id: 83, name: 'Nhãn', categoryId: 8 },
  { id: 84, name: 'Nước cốt dừa (lỏng)', categoryId: 5 },
  { id: 85, name: 'Đường', categoryId: 5 },
  { id: 86, name: 'Đá bào', categoryId: 5 },
  { id: 87, name: 'Nước', categoryId: 5 },
  { id: 88, name: 'Dưa cải chua', categoryId: 2 },
  { id: 89, name: 'Gạch cua', categoryId: 3 },
  { id: 90, name: 'Sườn sụn', categoryId: 1 },
  { id: 91, name: 'Hoa chuối', categoryId: 2 },
  { id: 92, name: 'Dầu ăn', categoryId: 5 },
  { id: 93, name: 'Bột chiên giòn', categoryId: 5 },
  { id: 94, name: 'Lá é', categoryId: 2 },
  { id: 95, name: 'Thuốc bắc', categoryId: 5 },
  { id: 96, name: 'Bún lá', categoryId: 4 },
  { id: 97, name: 'Chả cốm', categoryId: 1 },
  { id: 98, name: 'Nem chua', categoryId: 1 },
  { id: 99, name: 'Dồi sụn', categoryId: 1 },
  { id: 100, name: 'Bánh phở tươi', categoryId: 4 },
  { id: 101, name: 'Dưa chuột', categoryId: 2 },
];

export const allDishes: Dish[] = [
  {
    id: 1,
    name: 'Canh chua cá lóc',
    description: 'Món canh truyền thống miền Nam, vị chua thanh từ me, ngọt từ cá lóc và rau thơm.',
    imageUrl: getPlaceholderImage('canh_chua_ca_loc.jpg'),
    imageHint: 'sour fish soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Cá lóc, cà chua, dứa, đậu bắp, bạc hà, giá đỗ, me vắt, nước mắm, đường, dầu ăn, hành, tỏi, ớt, rau om, ngò gai. Cách làm: 1. Sơ chế cá lóc, ướp gia vị. 2. Phi thơm hành tỏi, xào cà chua, dứa. 3. Cho nước vào nấu sôi, thêm me vắt. 4. Cho cá vào nấu chín, thêm rau. 5. Nêm nếm vừa ăn, rắc rau thơm.',
    gmapsUrl: null,
  },
  {
    id: 2,
    name: 'Gà xào sả ớt',
    description: 'Thịt gà mềm ngọt, thấm vị sả ớt thơm lừng, đậm đà, ăn kèm cơm nóng.',
    imageUrl: getPlaceholderImage('ga_xao_sa_ot.jpg'),
    imageHint: 'lemongrass chicken',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Thịt gà, sả băm, ớt băm, tỏi băm, hành tím băm, nước mắm, đường, hạt nêm, dầu ăn. Cách làm: 1. Gà chặt miếng vừa ăn, ướp gia vị. 2. Phi thơm sả, ớt, tỏi, hành. 3. Cho gà vào xào săn, nêm nếm gia vị. 4. Xào đến khi gà chín và thấm đều gia vị.',
    gmapsUrl: null,
  },
  {
    id: 3,
    name: 'Đậu phụ sốt cà chua',
    description: 'Đậu phụ mềm, béo ngậy quyện với sốt cà chua chua ngọt, món ăn dân dã mà ngon miệng.',
    imageUrl: getPlaceholderImage('dau_phu_sot_ca_chua.jpg'),
    imageHint: 'tofu tomato sauce',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Đậu phụ, cà chua, hành lá, tỏi băm, nước mắm, đường, hạt nêm, dầu ăn. Cách làm: 1. Đậu phụ cắt miếng, chiên vàng. 2. Phi thơm tỏi, cho cà chua vào xào nhuyễn. 3. Thêm nước, nêm nếm gia vị. 4. Cho đậu phụ vào om, rắc hành lá.',
    gmapsUrl: null,
  },
  {
    id: 4,
    name: 'Sườn xào chua ngọt',
    description: 'Sườn heo giòn sần sật, thấm vị chua ngọt hài hòa, món ăn khoái khẩu của nhiều gia đình.',
    imageUrl: getPlaceholderImage('suon_xao_chua_ngot.jpg'),
    imageHint: 'sweet sour pork ribs',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Sườn non, hành tây, ớt chuông, tỏi băm, dấm, đường, nước mắm, tương ớt, bột năng. Cách làm: 1. Sườn luộc sơ, chiên vàng. 2. Pha nước sốt chua ngọt. 3. Xào hành tây, ớt chuông. 4. Cho sườn vào đảo đều với sốt, rắc tiêu.',
    gmapsUrl: null,
  },
  {
    id: 5,
    name: 'Canh bí đao thịt băm',
    description: 'Canh bí đao thanh mát, ngọt nước với thịt băm, giải nhiệt ngày hè.',
    imageUrl: getPlaceholderImage('canh_bi_dao_thit_bam.jpg'),
    imageHint: 'winter melon soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bí đao, thịt băm, hành tím, nước mắm, hạt nêm, tiêu, hành lá. Cách làm: 1. Bí đao gọt vỏ, thái miếng. 2. Ướp thịt băm. 3. Phi thơm hành, cho thịt vào xào. 4. Đổ nước vào nấu sôi, cho bí đao vào nấu chín, nêm nếm.',
    gmapsUrl: null,
  },
  {
    id: 6,
    name: 'Cơm chiên hải sản',
    description: 'Cơm rang tơi xốp, đầy ắp tôm, mực, rau củ, thơm lừng và đậm đà.',
    imageUrl: getPlaceholderImage('com_chien_hai_san.jpg'),
    imageHint: 'seafood fried rice',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Cơm nguội, tôm, mực, trứng, đậu Hà Lan, cà rốt, hành tây, tỏi băm, nước tương, dầu hào, dầu ăn. Cách làm: 1. Sơ chế hải sản, rau củ. 2. Phi thơm tỏi, cho hải sản vào xào. 3. Cho cơm vào rang, thêm trứng, rau củ. 4. Nêm nếm gia vị, đảo đều.',
    gmapsUrl: null,
  },
  {
    id: 7,
    name: 'Bò lúc lắc',
    description: 'Thịt bò mềm, thơm nức mùi bơ tỏi, ăn kèm rau xà lách và khoai tây chiên.',
    imageUrl: getPlaceholderImage('bo_luc_lac.jpg'),
    imageHint: 'shaking beef',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Thịt bò thăn, hành tây, ớt chuông, tỏi băm, dầu hào, dầu ăn, bơ, xì dầu, đường, hạt tiêu. Cách làm: 1. Bò thái vuông, ướp gia vị. 2. Xào hành tây, ớt chuông. 3. Phi thơm tỏi, cho bò vào xào nhanh lửa lớn. 4. Đảo đều, nêm nếm, thêm bơ.',
    gmapsUrl: null,
  },
  {
    id: 8,
    name: 'Canh nấm',
    description: 'Canh nấm thanh đạm, giàu dinh dưỡng, phù hợp cho những ai muốn ăn nhẹ nhàng.',
    imageUrl: getPlaceholderImage('canh_nam.jpg'),
    imageHint: 'mushroom soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Các loại nấm (nấm rơm, nấm kim châm, nấm đùi gà), đậu phụ, cà rốt, hành lá, hạt nêm chay. Cách làm: 1. Sơ chế nấm, đậu phụ, cà rốt. 2. Phi thơm hành, cho cà rốt vào xào. 3. Đổ nước, cho nấm và đậu phụ vào nấu chín, nêm nếm.',
    gmapsUrl: null,
  },
  {
    id: 9,
    name: 'Tôm rim thịt ba chỉ',
    description: 'Tôm và thịt ba chỉ rim keo với nước mắm đường, món ăn đậm đà đưa cơm.',
    imageUrl: getPlaceholderImage('tom_rim_thit.jpg'),
    imageHint: 'braised shrimp pork',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Tôm tươi, thịt ba chỉ, nước mắm, đường, hạt tiêu, tỏi băm, hành tím băm, ớt. Cách làm: 1. Sơ chế tôm, thịt ba chỉ. 2. Phi thơm tỏi hành, cho thịt vào rang cháy cạnh. 3. Cho tôm vào đảo, thêm nước mắm, đường, nước màu, rim đến khi keo lại.',
    gmapsUrl: null,
  },
  {
    id: 10,
    name: 'Cải thảo xào tỏi',
    description: 'Cải thảo giòn ngọt xào tỏi thơm lừng, món rau đơn giản nhưng ngon miệng.',
    imageUrl: getPlaceholderImage('cai_thao_xao_toi.jpg'),
    imageHint: 'stir-fried napa cabbage',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Cải thảo, tỏi băm, dầu ăn, hạt nêm, nước tương. Cách làm: 1. Cải thảo rửa sạch, thái miếng. 2. Phi thơm tỏi, cho cải thảo vào xào nhanh lửa lớn. 3. Nêm nếm gia vị, đảo đều.',
    gmapsUrl: null,
  },
  {
    id: 11,
    name: 'Cháo gà',
    description: 'Cháo gà nóng hổi, thơm ngon, bổ dưỡng, rất hợp khi trời se lạnh hoặc bồi bổ.',
    imageUrl: getPlaceholderImage('chao_ga.jpg'),
    imageHint: 'chicken congee',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Gạo tẻ, thịt gà, hành lá, gừng, hành tím, hạt tiêu, nước mắm. Cách làm: 1. Luộc gà, lấy nước dùng và xé thịt gà. 2. Vo gạo, cho vào nước luộc gà nấu thành cháo. 3. Khi cháo chín, cho thịt gà xé, hành lá, gừng thái sợi, nêm nếm.',
    gmapsUrl: null,
  },
  {
    id: 12,
    name: 'Gỏi gà bắp cải',
    description: 'Món gỏi thanh mát, chua ngọt, giòn sần sật với thịt gà xé phay và bắp cải.',
    imageUrl: getPlaceholderImage('goi_ga_bap_cai.jpg'),
    imageHint: 'chicken cabbage salad',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Thịt gà luộc, bắp cải, cà rốt, hành tây, rau răm, lạc rang, nước mắm, đường, chanh, tỏi, ớt. Cách làm: 1. Xé thịt gà, thái sợi bắp cải, cà rốt, hành tây. 2. Pha nước trộn gỏi chua ngọt. 3. Trộn đều các nguyên liệu với nước trộn, rắc lạc rang.',
    gmapsUrl: null,
  },
  {
    id: 13,
    name: 'Cá diêu hồng sốt cà chua',
    description: 'Cá diêu hồng chiên giòn, sốt cà chua đậm đà, chua ngọt.',
    imageUrl: getPlaceholderImage('ca_dieu_hong_sot_ca_chua.jpg'),
    imageHint: 'fish tomato sauce',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Cá diêu hồng, cà chua, hành tím, tỏi băm, nước mắm, đường, hạt nêm, dầu ăn, hành lá. Cách làm: 1. Cá làm sạch, khứa vẩy, chiên vàng. 2. Phi thơm hành tỏi, cho cà chua vào xào nhuyễn. 3. Thêm nước, nêm gia vị, cho cá vào om. 4. Om đến khi cá thấm sốt, rắc hành lá.',
    gmapsUrl: null,
  },
  {
    id: 14,
    name: 'Vịt om sấu',
    description: 'Món vịt om sấu đặc trưng Hà Nội, vị chua thanh của sấu, thịt vịt mềm và thơm.',
    imageUrl: getPlaceholderImage('vit_om_sau.jpg'),
    imageHint: 'duck dracontomelon soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Thịt vịt, sấu, khoai sọ, hành tím, tỏi, sả, gừng, nước mắm, đường, hạt nêm, rau ngổ, mùi tàu. Cách làm: 1. Vịt sơ chế sạch, ướp gia vị. 2. Xào thịt vịt với hành, tỏi, sả, gừng. 3. Thêm sấu, khoai sọ, nước vào om đến khi vịt mềm. 4. Nêm nếm, rắc rau thơm.',
    gmapsUrl: null,
  },
  {
    id: 15,
    name: 'Nghêu hấp sả',
    description: 'Nghêu hấp với sả ớt thơm lừng, vị cay nhẹ, ngọt tự nhiên của nghêu.',
    imageUrl: getPlaceholderImage('ngheu_hap_sa.jpg'),
    imageHint: 'steamed clams lemongrass',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Nghêu, sả cây, ớt, gừng, lá chanh, nước mắm, đường. Cách làm: 1. Nghêu ngâm rửa sạch. 2. Sả đập dập, ớt thái lát, gừng thái sợi. 3. Xếp sả, gừng, ớt, lá chanh dưới đáy nồi, cho nghêu lên trên. 4. Hấp nhanh đến khi nghêu mở miệng, nêm nếm.',
    gmapsUrl: null,
  },
  {
    id: 16,
    name: 'Mì Ý sốt bò băm',
    description: 'Món mì Ý quen thuộc với sốt bò băm đậm đà, phô mai béo ngậy.',
    imageUrl: getPlaceholderImage('mi_y_sot_bo_bam.jpg'),
    imageHint: 'spaghetti bolognese',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Mì Ý, thịt bò băm, cà chua, hành tây, tỏi băm, tương cà, dầu ô liu, lá oregano khô, phô mai parmesan. Cách làm: 1. Luộc mì Ý. 2. Phi thơm tỏi hành, cho thịt bò băm vào xào. 3. Thêm cà chua, tương cà, oregano, nấu thành sốt. 4. Trộn mì với sốt, rắc phô mai.',
    gmapsUrl: null,
  },
  {
    id: 17,
    name: 'Sinh tố xoài',
    description: 'Sinh tố xoài mát lạnh, thơm ngon, bổ dưỡng, đơn giản dễ làm.',
    imageUrl: getPlaceholderImage('sinh_to_xoai.jpg'),
    imageHint: 'mango smoothie',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Xoài chín, sữa tươi, sữa đặc (tùy chọn), đá viên. Cách làm: 1. Xoài gọt vỏ, cắt miếng. 2. Cho xoài, sữa tươi, sữa đặc, đá viên vào máy xay sinh tố. 3. Xay nhuyễn và thưởng thức.',
    gmapsUrl: null,
  },
  {
    id: 18,
    name: 'Salad bơ tôm',
    description: 'Salad bơ tôm tươi mát, giàu dinh dưỡng với vị béo của bơ, ngọt của tôm.',
    imageUrl: getPlaceholderImage('salad_bo_tom.jpg'),
    imageHint: 'avocado shrimp salad',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bơ, tôm luộc, xà lách, cà chua bi, dưa chuột, dầu ô liu, dấm balsamic, muối, tiêu. Cách làm: 1. Sơ chế tôm, rau củ. 2. Bơ thái miếng. 3. Pha sốt trộn salad. 4. Trộn đều các nguyên liệu với sốt.',
    gmapsUrl: null,
  },
  {
    id: 19,
    name: 'Sữa chua dầm hoa quả',
    description: 'Sữa chua mát lạnh kết hợp với các loại hoa quả tươi, món tráng miệng giải nhiệt.',
    imageUrl: getPlaceholderImage('sua_chua_hoa_qua.jpg'),
    imageHint: 'yogurt fruit salad',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Sữa chua, sữa đặc, các loại hoa quả tươi (xoài, dâu tây, kiwi, dưa hấu, thanh long), đá bào. Cách làm: 1. Hoa quả thái hạt lựu. 2. Xếp hoa quả vào ly, thêm sữa chua, sữa đặc, đá bào. 3. Trộn đều và thưởng thức.',
    gmapsUrl: null,
  },
  {
    id: 20,
    name: 'Cháo yến mạch',
    description: 'Cháo yến mạch dễ làm, tốt cho sức khỏe, có thể ăn kèm trái cây hoặc thịt.',
    imageUrl: getPlaceholderImage('chao_yen_mach.jpg'),
    imageHint: 'oatmeal congee',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Yến mạch, sữa tươi hoặc nước, trái cây tươi (chuối, táo) hoặc thịt băm. Cách làm: 1. Cho yến mạch và sữa/nước vào nồi, đun nhỏ lửa. 2. Nấu đến khi yến mạch nở mềm. 3. Thêm trái cây hoặc thịt băm, nêm nếm.',
    gmapsUrl: null,
  },
  {
    id: 21,
    name: 'Bún đậu mắm tôm',
    description: 'Đĩa bún đậu thập cẩm gồm bún lá, đậu rán giòn, chả cốm, nem chua, dồi sụn và mắm tôm pha chuẩn vị.',
    imageUrl: getPlaceholderImage('bun_dau_mam_tom.jpg'),
    imageHint: 'tofu shrimp paste',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bún lá, đậu phụ, chả cốm, nem chua rán, dồi sụn, rau sống, mắm tôm, đường, chanh, ớt, dầu ăn. Cách làm: 1. Rán đậu, chả cốm, nem chua, dồi sụn. 2. Pha mắm tôm với đường, chanh, ớt, dầu nóng. 3. Bày bún, đậu, chả, rau sống ra đĩa, chấm mắm tôm.',
    gmapsUrl: null,
  },
  {
    id: 22,
    name: 'Bún thang',
    description: 'Món bún thang cầu kỳ, thanh tao với nước dùng trong, thịt gà, trứng tráng, giò lụa.',
    imageUrl: getPlaceholderImage('bun_thang.jpg'),
    imageHint: 'vermicelli soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bún, thịt gà, trứng gà, giò lụa, tôm khô, nấm hương, hành khô, rau răm, mùi tàu, dấm bỗng, mắm tôm (tùy chọn). Cách làm: 1. Nấu nước dùng gà. 2. Gà xé, trứng tráng thái sợi, giò thái sợi. 3. Bày bún, các topping vào bát, chan nước dùng nóng. 4. Thêm rau thơm, dấm bỗng.',
    gmapsUrl: null,
  },
  {
    id: 23,
    name: 'Nem lụi',
    description: 'Nem lụi nướng thơm lừng, ăn kèm rau sống, bánh đa và nước chấm đậu phộng đặc trưng.',
    imageUrl: getPlaceholderImage('nem_lui.jpg'),
    imageHint: 'lemongrass pork skewers',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Thịt heo xay, mỡ heo, bì heo, thính gạo, đường, nước mắm, hạt tiêu, tỏi băm, sả băm, que tre. Cách làm: 1. Trộn đều thịt, mỡ, bì, gia vị, thính. 2. Bọc hỗn hợp vào que tre, nướng chín vàng. 3. Chuẩn bị rau sống, bánh đa, nước chấm đậu phộng.',
    gmapsUrl: null,
  },
  {
    id: 24,
    name: 'Gà tần thuốc bắc',
    description: 'Gà tần thuốc bắc bổ dưỡng, thơm lừng mùi thuốc bắc, thịt gà mềm tan.',
    imageUrl: getPlaceholderImage('ga_tan_thuoc_bac.jpg'),
    imageHint: 'herbal chicken soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Gà ta, gói thuốc bắc hầm gà, hạt sen, nấm hương, gừng, hành tím, gia vị. Cách làm: 1. Gà làm sạch. 2. Ướp gà với gia vị. 3. Cho gà, thuốc bắc, hạt sen, nấm hương, gừng vào nồi, đổ nước, tần đến khi gà mềm nhừ.',
    gmapsUrl: null,
  },
  {
    id: 25,
    name: 'Bánh xèo',
    description: 'Bánh xèo giòn rụm với nhân tôm thịt, giá đỗ, ăn kèm rau sống và nước chấm chua ngọt.',
    imageUrl: getPlaceholderImage('banh_xeo.jpg'),
    imageHint: 'vietnamese pancake',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bột bánh xèo, tôm, thịt ba chỉ, giá đỗ, hành lá, nước cốt dừa, dầu ăn. Cách làm: 1. Pha bột bánh xèo. 2. Xào nhân tôm, thịt, giá đỗ. 3. Tráng bánh xèo trên chảo nóng, cho nhân vào. 4. Gấp bánh, ăn kèm rau sống và nước chấm.',
    gmapsUrl: null,
  },
  {
    id: 26,
    name: 'Bún riêu cua',
    description: 'Bún riêu cua đồng đậm đà hương vị truyền thống, gạch cua béo ngậy, đậu phụ và huyết.',
    imageUrl: getPlaceholderImage('bun_rieu_cua.jpg'),
    imageHint: 'crab noodle soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bún, cua đồng, cà chua, đậu phụ, trứng vịt, giò tai, mắm tôm, hành khô, hành lá, rau sống. Cách làm: 1. Giã cua, lọc lấy nước. 2. Nấu riêu cua với gạch cua, trứng, thịt băm. 3. Xào cà chua, cho vào nồi nước cua. 4. Rán đậu, chuẩn bị rau sống, bún.',
    gmapsUrl: null,
  },
  {
    id: 27,
    name: 'Lẩu gà lá é',
    description: 'Nồi lẩu gà lá é thơm nồng mùi lá é, thịt gà tươi ngon, vị cay nhẹ, rất hợp tụ tập.',
    imageUrl: getPlaceholderImage('lau_ga_la_e.jpg'),
    imageHint: 'chicken hotpot e-leaf',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Thịt gà, lá é, măng tươi (hoặc khô), nấm, sả, ớt, gừng, gia vị lẩu, bún tươi, rau ăn kèm. Cách làm: 1. Chặt gà miếng vừa ăn, ướp gia vị. 2. Phi thơm sả, gừng, ớt. 3. Xào gà, đổ nước dùng, thêm lá é, măng, nấm. 4. Nêm nếm vừa ăn, ăn kèm bún và rau.',
    gmapsUrl: null,
  },
  {
    id: 28,
    name: 'Cá kho tộ',
    description: 'Món cá kho tộ đậm đà, thịt cá chắc, thấm vị nước mắm đường keo lại.',
    imageUrl: getPlaceholderImage('ca_kho_to.jpg'),
    imageHint: 'caramelized fish',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Cá lóc/cá basa, thịt ba chỉ, nước mắm, đường, nước màu, tỏi, ớt, tiêu, hành lá. Cách làm: 1. Cá làm sạch, cắt khúc. Thịt ba chỉ thái miếng. 2. Ướp cá và thịt với gia vị. 3. Kho cá với thịt trong tộ đất đến khi nước keo lại, cá thấm. 4. Rắc hành lá, tiêu.',
    gmapsUrl: null,
  },
  {
    id: 29,
    name: 'Gỏi cuốn',
    description: 'Những cuốn gỏi tươi mát với tôm, thịt, bún, rau sống, chấm nước chấm đậu phộng hoặc mắm nêm.',
    imageUrl: getPlaceholderImage('goi_cuon.jpg'),
    imageHint: 'spring rolls',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bánh tráng, tôm luộc, thịt ba chỉ luộc, bún tươi, xà lách, húng quế, hẹ, lạc rang, nước mắm pha chua ngọt hoặc mắm nêm. Cách làm: 1. Sơ chế tôm, thịt, rau sống. 2. Trải bánh tráng, xếp rau, bún, tôm, thịt. 3. Cuốn chặt tay, chấm nước chấm.',
    gmapsUrl: null,
  },
  {
    id: 30,
    name: 'Canh măng sườn',
    description: 'Canh măng sườn chua nhẹ, thanh mát, sườn mềm, măng giòn.',
    imageUrl: getPlaceholderImage('canh_mang_suon.jpg'),
    imageHint: 'bamboo shoot soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Sườn heo, măng tươi (hoặc măng khô), cà chua, hành lá, rau mùi, nước mắm, hạt nêm. Cách làm: 1. Sườn chặt khúc, luộc sơ. 2. Măng thái lát, luộc kỹ. 3. Xào cà chua, cho sườn vào đảo. 4. Đổ nước, cho măng vào nấu, nêm nếm.',
    gmapsUrl: null,
  },
  {
    id: 31,
    name: 'Chè khoai môn',
    description: 'Món chè ngọt bùi với khoai môn dẻo thơm, nước cốt dừa béo ngậy.',
    imageUrl: getPlaceholderImage('che_khoai_mon.jpg'),
    imageHint: 'taro sweet soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Khoai môn, đường, nước cốt dừa, bột năng (hoặc bột khoai), dừa nạo. Cách làm: 1. Khoai môn hấp chín, tán nhuyễn. 2. Nấu nước cốt dừa với đường. 3. Cho khoai môn vào nấu cùng, thêm bột năng tạo độ sánh. 4. Ăn nóng hoặc lạnh với dừa nạo.',
    gmapsUrl: null,
  },
  {
    id: 32,
    name: 'Xôi xéo',
    description: 'Xôi xéo dẻo thơm, béo ngậy với mỡ hành, ruốc và hành phi giòn tan.',
    imageUrl: getPlaceholderImage('xoi_xeo.jpg'),
    imageHint: 'sticky rice',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Gạo nếp, đậu xanh, mỡ gà (hoặc dầu ăn), hành tím, nước cốt dừa, muối, đường. Cách làm: 1. Nếp ngâm, hấp chín. Đậu xanh đồ chín, đánh nhuyễn. 2. Phi thơm hành tím với mỡ gà, cho đậu xanh vào xào, nêm nếm. 3. Xới xôi, cho đậu xanh lên trên, thêm mỡ hành, ruốc, hành phi.',
    gmapsUrl: null,
  },
  {
    id: 33,
    name: 'Bún chả cá rô',
    description: 'Bún chả cá rô đồng, nước dùng ngọt thanh, chả cá dai ngon, ăn kèm rau sống.',
    imageUrl: getPlaceholderImage('bun_cha_ca_ro.jpg'),
    imageHint: 'fish cake noodles',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bún, cá rô đồng, thịt nạc vai băm, thì là, hành lá, cà chua, dấm bỗng, nước mắm, hạt nêm, rau sống. Cách làm: 1. Luộc cá, gỡ thịt, lọc xương nấu nước dùng. 2. Trộn thịt cá với thịt băm, thì là, gia vị làm chả. 3. Nấu nước dùng với cà chua, dấm bỗng, nêm nếm. 4. Bày bún, chả cá, rau sống, chan nước dùng.',
    gmapsUrl: null,
  },
  {
    id: 34,
    name: 'Nộm hoa chuối tai heo',
    description: 'Món nộm giòn mát, chua cay mặn ngọt với hoa chuối, tai heo sần sật, đậu phộng rang.',
    imageUrl: getPlaceholderImage('nom_hoa_chuoi_tai_heo.jpg'),
    imageHint: 'banana blossom salad',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Hoa chuối, tai heo, cà rốt, dưa chuột, rau thơm, lạc rang, nước mắm, đường, chanh, tỏi, ớt. Cách làm: 1. Hoa chuối thái sợi, ngâm nước dấm. Tai heo luộc chín, thái mỏng. 2. Pha nước trộn nộm chua ngọt. 3. Trộn đều các nguyên liệu với nước trộn, rắc lạc rang.',
    gmapsUrl: null,
  },
  {
    id: 35,
    name: 'Lẩu thái',
    description: 'Nồi lẩu Thái chua cay đậm đà, hải sản tươi ngon và rau củ phong phú.',
    imageUrl: getPlaceholderImage('lau_thai.jpg'),
    imageHint: 'thai hotpot',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Xương ống, tôm, mực, ngao, thịt bò, nấm, rau muống, cải thảo, bún, gói gia vị lẩu Thái, sả, ớt, gừng. Cách làm: 1. Nấu nước dùng xương. 2. Phi thơm sả, gừng, ớt, cho gói gia vị lẩu Thái vào. 3. Đổ nước dùng vào, nêm nếm. 4. Nhúng hải sản, thịt, rau ăn kèm.',
    gmapsUrl: null,
  },
  {
    id: 36,
    name: 'Miến trộn gà',
    description: 'Miến dai ngon trộn cùng thịt gà xé, rau thơm, hành phi và nước sốt chua ngọt.',
    imageUrl: getPlaceholderImage('mien_tron_ga.jpg'),
    imageHint: 'chicken glass noodles',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Miến dong, thịt gà luộc, dưa chuột, cà rốt, giá đỗ, rau thơm, lạc rang, hành phi, nước mắm, đường, chanh, tỏi, ớt, xì dầu. Cách làm: 1. Luộc miến, luộc gà, xé thịt. 2. Sơ chế rau củ. 3. Pha nước trộn miến chua ngọt. 4. Trộn đều miến, gà, rau củ với nước trộn, rắc lạc, hành phi.',
    gmapsUrl: null,
  },
  {
    id: 37,
    name: 'Cơm tấm sườn bì chả',
    description: 'Món cơm tấm đặc trưng miền Nam với sườn nướng, bì heo, chả trứng và nước mắm.',
    imageUrl: getPlaceholderImage('com_tam_suon_bi_cha.jpg'),
    imageHint: 'broken rice',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Gạo tấm, sườn cốt lết, bì heo, trứng gà, thịt băm, nước mắm, đường, tỏi, ớt, dưa chuột, cà chua. Cách làm: 1. Nấu cơm tấm. 2. Ướp sườn, nướng chín. 3. Làm bì heo, chả trứng. 4. Pha nước mắm chua ngọt. 5. Bày cơm, sườn, bì, chả, rau sống, chan nước mắm.',
    gmapsUrl: null,
  },
  {
    id: 38,
    name: 'Gà rang gừng',
    description: 'Gà rang gừng thơm lừng, thịt gà mềm, đậm đà, cay nhẹ, ăn kèm cơm nóng.',
    imageUrl: getPlaceholderImage('ga_rang_gung.jpg'),
    imageHint: 'ginger fried chicken',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Thịt gà, gừng, hành tím, nước mắm, đường, hạt nêm, tiêu, dầu ăn. Cách làm: 1. Gà chặt miếng, ướp gia vị. 2. Phi thơm hành tím, gừng, cho gà vào rang. 3. Rang đến khi gà săn lại, thấm gia vị, rắc tiêu.',
    gmapsUrl: null,
  },
  {
    id: 39,
    name: 'Chả lá lốt',
    description: 'Chả lá lốt thơm nức mùi lá lốt, nhân thịt heo đậm đà, chiên vàng giòn.',
    imageUrl: getPlaceholderImage('cha_la_lot.jpg'),
    imageHint: 'lolot leaf beef',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Lá lốt, thịt nạc vai băm, mộc nhĩ, hành tím, nước mắm, hạt nêm, tiêu, dầu ăn. Cách làm: 1. Trộn thịt băm, mộc nhĩ, hành tím, gia vị. 2. Trải lá lốt, cho nhân vào cuộn tròn. 3. Chiên chả lá lốt vàng giòn.',
    gmapsUrl: null,
  },
  {
    id: 40,
    name: 'Lươn om chuối đậu',
    description: 'Món lươn om chuối đậu béo ngậy, đậm đà hương vị đồng quê, lươn mềm, chuối bùi.',
    imageUrl: getPlaceholderImage('luon_om_chuoi_dau.jpg'),
    imageHint: 'eel banana stew',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Lươn, chuối xanh, đậu phụ, thịt ba chỉ, mẻ, mắm tôm, tỏi, ớt, hành lá, tía tô, lá lốt, nước cốt dừa. Cách làm: 1. Sơ chế lươn. Chuối xanh tước vỏ, thái khúc. Đậu phụ rán vàng. 2. Ướp lươn, thịt ba chỉ. 3. Xào thịt, lươn, chuối, đậu. 4. Thêm mẻ, mắm tôm, nước cốt dừa, om đến khi chín mềm.',
    gmapsUrl: null,
  },
  {
    id: 41,
    name: 'Mì tôm xào bò',
    description: 'Món mì tôm quen thuộc được nâng tầm với thịt bò mềm, rau củ và nước sốt đậm đà.',
    imageUrl: getPlaceholderImage('mi_tom_xao_bo.jpg'),
    imageHint: 'noodle stir-fry beef',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Mì tôm, thịt bò, cải ngọt, hành tây, cà rốt, tỏi, dầu hào, nước tương, dầu ăn. Cách làm: 1. Trụng mì tôm. 2. Xào thịt bò. 3. Xào rau củ. 4. Trộn mì, thịt, rau củ với sốt, xào nhanh tay.',
    gmapsUrl: null,
  },
  {
    id: 42,
    name: 'Cơm rang dưa bò',
    description: 'Cơm rang tơi xốp, thơm lừng với dưa chua giòn sần sật và thịt bò mềm.',
    imageUrl: getPlaceholderImage('com_rang_dua_bo.jpg'),
    imageHint: 'beef fried rice',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Cơm nguội, thịt bò, dưa cải chua, trứng gà, tỏi, hành lá, nước tương, dầu ăn, hạt tiêu. Cách làm: 1. Xào thịt bò. 2. Phi thơm tỏi, cho cơm vào rang. 3. Thêm dưa cải, thịt bò, trứng, nêm nếm. 4. Rang đến khi cơm tơi, rắc hành lá.',
    gmapsUrl: null,
  },
  {
    id: 43,
    name: 'Xôi gấc',
    description: 'Xôi gấc dẻo thơm, đỏ au, tượng trưng cho may mắn, thường có trong các dịp lễ tết.',
    imageUrl: getPlaceholderImage('xoi_gac.jpg'),
    imageHint: 'red sticky rice',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Gạo nếp, gấc tươi, dừa nạo, đường, muối, rượu trắng. Cách làm: 1. Nếp ngâm. Gấc trộn rượu, bóp lấy thịt. 2. Trộn nếp với gấc, chút muối. 3. Hấp xôi, giữa chừng rắc đường, dừa nạo. Hấp đến khi chín dẻo.',
    gmapsUrl: null,
  },
  {
    id: 44,
    name: 'Bánh mì kẹp thịt',
    description: 'Món bánh mì kẹp thịt nguội hoặc thịt nướng quen thuộc, nhanh gọn và tiện lợi.',
    imageUrl: getPlaceholderImage('banh_mi_kep_thit.jpg'),
    imageHint: 'pork sandwich',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bánh mì, thịt nguội/thịt nướng, pate, dưa chuột, rau mùi, đồ chua (cà rốt, củ cải), ớt. Cách làm: 1. Xẻ bánh mì, phết pate. 2. Xếp thịt, dưa chuột, rau mùi, đồ chua. 3. Thêm ớt, nước sốt.',
    gmapsUrl: null,
  },
  {
    id: 45,
    name: 'Gỏi cuốn tôm thịt',
    description: 'Những cuốn gỏi thanh mát với tôm, thịt, bún, rau sống, chấm nước mắm chua ngọt.',
    imageUrl: getPlaceholderImage('goi_cuon_tom_thit.jpg'),
    imageHint: 'spring rolls shrimp',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bánh tráng, tôm luộc, thịt ba chỉ luộc, bún tươi, xà lách, húng quế, hẹ, lạc rang, nước mắm pha chua ngọt hoặc mắm nêm. Cách làm: 1. Sơ chế tôm, thịt, rau sống. 2. Trải bánh tráng, xếp rau, bún, tôm, thịt. 3. Cuốn chặt tay, chấm nước chấm.',
    gmapsUrl: null,
  },
  {
    id: 46,
    name: 'Bánh đa trộn',
    description: 'Món bánh đa trộn đặc trưng với thịt, rau thơm, hành phi và nước sốt đặc biệt.',
    imageUrl: getPlaceholderImage('banh_da_tron.jpg'),
    imageHint: 'mixed rice paper',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bánh đa khô, thịt bò/gà xé, rau thơm, giá đỗ, lạc rang, hành phi, nước mắm, đường, chanh, tỏi, ớt, xì dầu, dầu ăn. Cách làm: 1. Trụng bánh đa. 2. Trộn bánh đa với thịt, rau thơm, giá đỗ. 3. Pha nước trộn. 4. Rưới nước trộn, rắc lạc, hành phi.',
    gmapsUrl: null,
  },
  {
    id: 47,
    name: 'Cá chép om dưa',
    description: 'Cá chép om dưa chua thanh, cá mềm ngọt, ăn kèm bún hoặc cơm.',
    imageUrl: getPlaceholderImage('ca_chep_om_dua.jpg'),
    imageHint: 'carp pickle soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Cá chép, dưa cải chua, cà chua, thịt ba chỉ, hành, tỏi, ớt, thì là, hành lá, nước mắm, hạt nêm, dầu ăn. Cách làm: 1. Cá làm sạch, chiên sơ. 2. Phi thơm hành tỏi, xào thịt ba chỉ, dưa chua, cà chua. 3. Đổ nước, cho cá vào om. 4. Om đến khi cá chín mềm, thấm vị, rắc rau thơm.',
    gmapsUrl: null,
  },
  {
    id: 48,
    name: 'Bún ngan',
    description: 'Món bún ngan đậm đà, nước dùng ngọt thanh từ xương ngan, thịt ngan mềm.',
    imageUrl: getPlaceholderImage('bun_ngan.jpg'),
    imageHint: 'duck noodle soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bún, thịt ngan, măng tươi (hoặc khô), hành lá, mùi tàu, hành phi, gừng, nước mắm, hạt nêm. Cách làm: 1. Luộc ngan, lấy nước dùng. Thịt ngan chặt miếng. 2. Măng luộc kỹ, xào. 3. Nấu nước dùng ngan với măng, nêm nếm. 4. Bày bún, thịt ngan, măng, hành lá, mùi tàu, chan nước dùng.',
    gmapsUrl: null,
  },
  {
    id: 49,
    name: 'Súp cua',
    description: 'Súp cua nóng hổi, sánh mịn với thịt cua ngọt, trứng cút, nấm hương.',
    imageUrl: getPlaceholderImage('sup_cua.jpg'),
    imageHint: 'crab soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Thịt cua, xương gà (nấu nước dùng), trứng cút, nấm hương, trứng gà, bột năng, hạt tiêu, dầu mè, hành lá, rau mùi. Cách làm: 1. Nấu nước dùng gà. 2. Cho thịt cua, nấm hương, trứng cút vào nấu. 3. Đánh tan trứng gà, đổ từ từ vào tạo vân. 4. Hòa bột năng với nước, đổ vào tạo độ sánh. Nêm nếm.',
    gmapsUrl: null,
  },
  {
    id: 50,
    name: 'Bánh tráng trộn',
    description: 'Món ăn vặt đường phố nổi tiếng với bánh tráng, xoài, trứng cút, khô bò, rau răm, nước sốt.',
    imageUrl: getPlaceholderImage('banh_trang_tron.jpg'),
    imageHint: 'mixed rice paper salad',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bánh tráng cắt sợi, xoài xanh, trứng cút luộc, khô bò, tép khô, rau răm, đậu phộng rang, hành phi, nước sốt me/tắc. Cách làm: 1. Sơ chế các nguyên liệu. 2. Pha nước sốt. 3. Cho tất cả vào tô, rưới sốt, trộn đều.',
    gmapsUrl: null,
  },
  {
    id: 51,
    name: 'Sinh tố dưa hấu',
    description: 'Sinh tố dưa hấu mát lạnh, giải khát tức thì trong những ngày nóng bức.',
    imageUrl: getPlaceholderImage('sinh_to_dua_hau.jpg'),
    imageHint: 'watermelon smoothie',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Dưa hấu, đường (tùy chọn), đá viên. Cách làm: 1. Dưa hấu gọt vỏ, bỏ hạt, thái miếng. 2. Cho dưa hấu, đường, đá viên vào máy xay sinh tố. 3. Xay nhuyễn và thưởng thức.',
    gmapsUrl: null,
  },
  {
    id: 52,
    name: 'Nước ép cam',
    description: 'Nước ép cam tươi mát, giàu vitamin C, tốt cho sức khỏe và làm đẹp.',
    imageUrl: getPlaceholderImage('nuoc_ep_cam.jpg'),
    imageHint: 'orange juice',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Cam tươi, đường (tùy chọn), đá viên. Cách làm: 1. Cam rửa sạch, cắt đôi. 2. Dùng máy ép cam hoặc vắt tay lấy nước cốt. 3. Thêm đường, đá viên tùy khẩu vị.',
    gmapsUrl: null,
  },
  {
    id: 53,
    name: 'Trà chanh',
    description: 'Trà chanh thơm lừng, vị chua ngọt hài hòa, là thức uống yêu thích của nhiều người trẻ.',
    imageUrl: getPlaceholderImage('tra_chanh.jpg'),
    imageHint: 'lemon tea',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Trà túi lọc/trà xanh, chanh tươi, đường, nước lọc, đá viên. Cách làm: 1. Pha trà. 2. Vắt chanh, pha nước đường. 3. Trộn trà, nước chanh đường, thêm đá.',
    gmapsUrl: null,
  },
  {
    id: 54,
    name: 'Rau câu dừa',
    description: 'Rau câu dừa thanh mát, ngọt nhẹ, béo ngậy mùi cốt dừa, món tráng miệng quen thuộc.',
    imageUrl: getPlaceholderImage('rau_cau_dua.jpg'),
    imageHint: 'coconut jelly',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bột rau câu dẻo, nước dừa tươi, nước cốt dừa, đường. Cách làm: 1. Hòa tan bột rau câu với đường và nước dừa. 2. Đun sôi hỗn hợp, cho nước cốt dừa vào. 3. Đổ ra khuôn, để nguội và đông lại.',
    gmapsUrl: null,
  },
  {
    id: 55,
    name: 'Chè bưởi',
    description: 'Chè bưởi ngọt ngào, giòn sần sật của cùi bưởi, béo ngậy của nước cốt dừa.',
    imageUrl: getPlaceholderImage('che_buoi.jpg'),
    imageHint: 'pomelo sweet soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Cùi bưởi, đậu xanh, bột năng, nước cốt dừa, đường, lá dứa (tùy chọn). Cách làm: 1. Sơ chế cùi bưởi, ngâm, vắt sạch đắng, áo bột năng. 2. Đậu xanh đồ chín. 3. Nấu nước cốt dừa với đường, lá dứa. 4. Cho cùi bưởi, đậu xanh vào, nấu sánh.',
    gmapsUrl: null,
  },
  {
    id: 56,
    name: 'Salad trái cây',
    description: 'Salad trái cây tươi ngon, đa dạng màu sắc, vị chua ngọt tự nhiên, rất tốt cho sức khỏe.',
    imageUrl: getPlaceholderImage('salad_trai_cay.jpg'),
    imageHint: 'fruit salad',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Các loại trái cây tươi (dưa hấu, dâu tây, kiwi, xoài, nho, thanh long), sữa chua không đường, mật ong (tùy chọn). Cách làm: 1. Trái cây gọt vỏ, thái miếng vừa ăn. 2. Trộn đều trái cây với sữa chua và mật ong.',
    gmapsUrl: null,
  },
  {
    id: 57,
    name: 'Kem bơ',
    description: 'Kem bơ béo ngậy, mịn màng, thơm lừng vị bơ tươi, món tráng miệng hấp dẫn.',
    imageUrl: getPlaceholderImage('kem_bo.jpg'),
    imageHint: 'avocado ice cream',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bơ sáp chín, sữa tươi, sữa đặc, đường, đá viên. Cách làm: 1. Bơ gọt vỏ, bỏ hạt, thái miếng. 2. Cho bơ, sữa tươi, sữa đặc, đường, đá viên vào máy xay. 3. Xay nhuyễn mịn, có thể cho vào tủ đông thêm.',
    gmapsUrl: null,
  },
  {
    id: 58,
    name: 'Sinh tố bơ chuối',
    description: 'Sinh tố bơ chuối bổ dưỡng, béo ngậy, ngọt dịu, cung cấp năng lượng tức thì.',
    imageUrl: getPlaceholderImage('sinh_to_bo_chuoi.jpg'),
    imageHint: 'avocado banana smoothie',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Bơ sáp chín, chuối chín, sữa tươi, sữa đặc (tùy chọn), đá viên. Cách làm: 1. Bơ và chuối gọt vỏ, thái miếng. 2. Cho bơ, chuối, sữa tươi, sữa đặc, đá viên vào máy xay. 3. Xay nhuyễn mịn.',
    gmapsUrl: null,
  },
  {
    id: 59,
    name: 'Hoa quả dầm',
    description: 'Các loại hoa quả tươi ngon cắt nhỏ, dầm với sữa chua, sữa đặc, đá bào, món ăn vặt được yêu thích.',
    imageUrl: getPlaceholderImage('hoa_qua_dam.jpg'),
    imageHint: 'mixed fruit yogurt',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Các loại trái cây (xoài, dưa hấu, thanh long, dâu tây...), sữa chua, sữa đặc, nước cốt dừa, đá bào. Cách làm: 1. Trái cây thái hạt lựu. 2. Cho trái cây, sữa chua, sữa đặc, nước cốt dừa, đá bào vào ly. 3. Trộn đều.',
    gmapsUrl: null,
  },
  {
    id: 60,
    name: 'Chè vải thiều',
    description: 'Chè vải thiều thanh mát, ngọt dịu, đặc trưng của mùa hè Việt Nam.',
    imageUrl: getPlaceholderImage('che_vai_thieu.jpg'),
    imageHint: 'lychee sweet soup',
    type: 'Nấu tại nhà',
    recipeOrAddress:
      'Nguyên liệu: Vải thiều tươi, đường, nước, đá viên. Cách làm: 1. Vải bóc vỏ, bỏ hạt. 2. Nấu nước đường. 3. Cho vải vào nước đường, đun nhẹ. 4. Để nguội, thêm đá khi ăn.',
    gmapsUrl: null,
  },
  {
    id: 61,
    name: 'Bún Chả Hương Liên',
    description: 'Đặc sản Hà Nội trứ danh với chả miếng, chả băm nướng thơm lừng, ăn kèm bún và nước chấm chua ngọt.',
    imageUrl: getPlaceholderImage('bun_cha_hl.jpg'),
    imageHint: 'restaurant interior',
    type: 'Quán ăn',
    recipeOrAddress: '24 Lê Văn Hưu, P. Ngô Thì Nhậm, Q. Hai Bà Trưng, Hà Nội',
    gmapsUrl: 'https://shopeefood.vn/thuong-hieu/bun-cha-huong-lien',
  },
  {
    id: 62,
    name: 'Phở Cuốn Hưng Bền',
    description: 'Phở cuốn thanh mát, chấm nước mắm chua ngọt.',
    imageUrl: getPlaceholderImage('pho_cuon_hb.jpg'),
    imageHint: 'restaurant food',
    type: 'Quán ăn',
    recipeOrAddress: '33 Phố Ngũ Xã, Trúc Bạch, Ba Đình, Hà Nội',
    gmapsUrl: 'https://shopeefood.vn/ha-noi/pho-cuon-hung-ben-118-tran-vu',
  },
  {
    id: 63,
    name: 'Bún Riêu Cua Hàng Bạc',
    description: 'Quán bún riêu cua lâu đời trong phố cổ, nước dùng đậm đà.',
    imageUrl: getPlaceholderImage('bun_rieu_hb.jpg'),
    imageHint: 'street food stall',
    type: 'Quán ăn',
    recipeOrAddress: '11 Hàng Bạc, Hoàn Kiếm, Hà Nội',
    gmapsUrl: 'https://www.foody.vn/ha-noi/bun-rieu-hang-bac',
  },
  {
    id: 64,
    name: 'Lẩu Riêu Cua Ngõ Gạch',
    description: 'Quán lẩu riêu cua truyền thống, nước dùng thanh ngọt, gạch cua béo ngậy.',
    imageUrl: getPlaceholderImage('lau_rieu_ngogach.jpg'),
    imageHint: 'hotpot restaurant',
    type: 'Quán ăn',
    recipeOrAddress: '18 Ngõ Gạch, Hàng Bồ, Hoàn Kiếm, Hà Nội',
    gmapsUrl: 'https://quananngonhanoi.com/top-10-quan-lau-rieu-cua-bap-bo-ha-noi-ngon-va-noi-tieng-nhat/',
  },
  {
    id: 65,
    name: 'Bún Ốc Bà Giun',
    description: 'Bún ốc truyền thống Hà Nội, vị chua thanh, ốc giòn sần sật.',
    imageUrl: getPlaceholderImage('bun_oc_bagiun.jpg'),
    imageHint: 'vietnamese restaurant',
    type: 'Quán ăn',
    recipeOrAddress: '37 Đặng Dung, Quán Thánh, Ba Đình, Hà Nội',
    gmapsUrl: 'https://shopeefood.vn/ha-noi/bun-oc-co-giang-dang-dung',
  },
  {
    id: 66,
    name: 'Chả Cá Lã Vọng',
    description: 'Quán chả cá lâu đời nhất, giữ nguyên hương vị truyền thống.',
    imageUrl: getPlaceholderImage('cha_ca_la_vong.jpg'),
    imageHint: 'historic restaurant',
    type: 'Quán ăn',
    recipeOrAddress: '14 Chả Cá, Hàng Bồ, Hoàn Kiếm, Hà Nội',
    gmapsUrl: 'https://shopeefood.vn/ha-noi/cha-ca-la-vong-cha-ca',
  },
  {
    id: 67,
    name: 'Bún Đậu Mắm Tôm Gốc Đa',
    description: 'Quán bún đậu mắm tôm đông khách ở phố cổ, mắm tôm chuẩn vị.',
    imageUrl: getPlaceholderImage('bun_dau_gocda.jpg'),
    imageHint: 'outdoor dining',
    type: 'Quán ăn',
    recipeOrAddress: '4 Ngõ Gạch, Hàng Buồm, Hoàn Kiếm, Hà Nội',
    gmapsUrl: 'https://www.foody.vn/ha-noi/bun-dau-mam-tom-ngo-gach',
  },
  {
    id: 68,
    name: 'Phở Gia Truyền Bát Đàn',
    description: 'Phở xếp hàng lâu nổi tiếng, nước dùng ngọt thanh, thịt bò tươi ngon.',
    imageUrl: getPlaceholderImage('pho_bat_dan.jpg'),
    imageHint: 'pho restaurant',
    type: 'Quán ăn',
    recipeOrAddress: '49 Bát Đàn, Cửa Đông, Hoàn Kiếm, Hà Nội',
    gmapsUrl: 'https://www.foody.vn/ha-noi/pho-gia-truyen',
  },
  {
    id: 69,
    name: 'Phở Gà Nguyệt',
    description: 'Phở gà ngon nổi tiếng với thịt gà dai, nước dùng trong veo.',
    imageUrl: getPlaceholderImage('pho_ga_nguyet.jpg'),
    imageHint: 'chicken pho restaurant',
    type: 'Quán ăn',
    recipeOrAddress: '5 Phủ Doãn, Hàng Trống, Hoàn Kiếm, Hà Nội',
    gmapsUrl: 'https://shopeefood.vn/ha-noi/pho-ga-nguyet-phu-doan',
  },
  {
    id: 70,
    name: 'Kem Tràng Tiền',
    description: 'Thương hiệu kem lâu đời của Hà Nội, nhiều hương vị.',
    imageUrl: getPlaceholderImage('kem_trang_tien.jpg'),
    imageHint: 'ice cream shop',
    type: 'Quán ăn',
    recipeOrAddress: '35 Tràng Tiền, Hoàn Kiếm, Hà Nội',
    gmapsUrl: 'https://www.kemtrangtien.vn/',
  },
  {
    id: 71,
    name: 'Sườn nướng ngũ vị',
    description: 'Sườn đẫm nướng sốt lên màu nâu đỏ, khi ăn róc xương, thịt mềm mọng nước mà không bị khô, nổi bật mùi thơm từ các gia vị.',
    imageUrl: getPlaceholderImage('suon_nuong_ngu_vi.jpg'),
    imageHint: 'grilled pork ribs',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Pha sốt: vắt nước hành, tỏi, đập sả, trộn với ngũ vị, dầu hào, tương ớt, tương cà, nước tương, dầu điều, đường, rượu, mật ong, muối, hạt nêm.Sơ chế sườn: ngâm nước muối loãng, rửa, thấm, rạch khe giữa dẻ.Ướp: quết 2/3 sốt lên sườn, ướp 2-3 giờ hoặc qua đêm.Nướng lần 1: bọc giấy bạc, nướng 50-60 phút ở 180°C.Nướng lần 2: bỏ giấy bạc, phết sốt còn lại, nướng 8-10 phút ở 200-220°C cho xém; nghỉ rồi dọn.',
    gmapsUrl: null,
  },
  {
    id: 72,
    name: 'Su hào xào mực',
    description: 'Đĩa xào khô ráo với su hào giòn ngọt quyện với mực mềm dai, ngọt tự nhiên. Đây là món ngày Tết cổ truyền của người dân làng gốm Bát Tràng, Hà Nội.',
    imageUrl: getPlaceholderImage('su_hao_xao_muc.jpg'),
    imageHint: 'stir-fried kohlrabi',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Chọn và sơ chế mực: Chọn mực câu thân dày, trắng nhẹ, lưng hồng tự nhiên, đầu dính chặt. Ngâm rượu trắng + gừng (hoặc bia) để khử mùi, mềm mực. Bỏ râu, mảng cứng, để ráo. Nướng thơm, gói giấy bạc, đập tách thớ rồi xé sợi nhỏ.Sao mực: Sao vàng mực xé sợi trên lửa nhỏ với mỡ lợn, nêm mắm truyền thống + đường.Xào: Phi thơm mỡ lợn, cho su hào + mực vào xào lửa vừa, đảo đều. Khi su hào chín giòn, nêm lại gia vị, rắc tiêu.',
    gmapsUrl: null,
  },
  {
    id: 73,
    name: 'Canh măng ngày Tết',
    description: 'Măng ngấu vị, giòn ngon, móng giò hầm vừa độ sần sật, nước canh ngọt tự nhiên. Đây là một trong những món canh tứ trụ trong cỗ Tết cổ truyền Hà Nội xưa.',
    imageUrl: getPlaceholderImage('canh_mang_ngay_tet.jpg'),
    imageHint: 'bamboo shoot soup',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Ngâm: 4-5 ngày nước vo gạo, thay 2 lần/ngày đến nước trong, măng mềm.Luộc: 4-5 lần 4-5 phút mở vung, ủ rửa đến nước trong, măng vàng nở; cắt gốc, thái vát.Nấu: om măng với nước dùng lửa nhỏ mở vung; hầm móng giò, ba chỉ, hớt bọt; nêm khi ngấu; xếp giò-măng-ba chỉ, thêm miến hành chần, chan nước.',
    gmapsUrl: null,
  },
  {
    id: 74,
    name: 'Giả hạnh nhân',
    description: 'Đây là món ăn cổ truyền thường thấy trong cỗ Tết của các gia đình phố cổ, vừa toát lên sự tinh tế, ý nhị vừa thể hiện được tinh thần tiết kiệm, sáng tạo của người Hà Nội xưa.',
    imageUrl: getPlaceholderImage('gia_hanh_nhan.jpg'),
    imageHint: 'chicken gizzard stir-fry',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Rang lạc: lửa nhỏ vàng thơm; chao mỡ nóng, vớt ráo.Sơ chế lòng gà: bóp muối rửa, luộc lửa nhỏ, rửa lại, thái lựu, ướp mắm muối tiêu.Chần củ quả: nước sôi muối chần nhanh su hào, củ đậu, cà rốt, đậu Hà Lan, ngâm lạnh, ráo.Xào: phi hành mỡ lợn, xào lòng gà chín để riêng; phi hành còn, xào cà rốt-su hào-củ đậu-đậu Hà Lan nêm gia vị; trút lòng gà đảo; thêm lạc, đầu hành; tắt bếp rắc lạc còn, rau mùi.',
    gmapsUrl: null,
  },
  {
    id: 75,
    name: 'Chả bì ớt xiêm xanh',
    description: 'Chả bì bóng đẹp, gói đều tay. Khi ăn vị ngọt mềm xen kẽ sần sật, dậy mùi thơm và vị the cay từ ớt xiêm xanh, hạt tiêu. Món ăn này nhâm nhi ngày Tết rất hợp vị, lại dễ làm.',
    imageUrl: getPlaceholderImage('cha_bi_ot_xiem.jpg'),
    imageHint: 'pork skin sausage',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Luộc bì: nước + gừng đập, hành, muối, giấm; sôi hớt bọt, lửa nhỏ chín; ngâm đá nguội; lạng mỡ, thái sợi.Trộn: bóp bì mắm mì chính, mát 10\'; thêm giò sống, tỏi, hành, tiêu, ớt xiêm xanh, mắm cốt; quết dẻo, lạnh 30\'.Gói: màng bọc rồi lá chuối, buộc thuôn.Hấp: lửa nhỏ 40-45\' xả hơi thỉnh thoảng; nguội mát; cắt tròn.',
    gmapsUrl: null,
  },
  {
    id: 76,
    name: 'Cá thu sốt cà chua',
    description: 'Thịt cá thu chắc thịt, sốt cà chua sánh, vị đậm đà. Món này ăn cùng rau sống, cơm nóng vào mùa đông rất hợp.',
    imageUrl: getPlaceholderImage('ca_thu_sot_ca_chua.jpg'),
    imageHint: 'mackerel tomato sauce',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Cá: cắt khúc, ngâm muối/chè xanh khử tanh, rửa thấm khô.Rán cá: dầu nóng rán đều mặt.Sốt: phi hành, thêm cà chua băm, tương cà, mắm, muối, đường nêm tiêu; đảo nhuyễn.Om: sốt sánh trút cá, lửa nhỏ + gừng ớt, nêm vừa; cuối thêm hành thì là đảo, tắt bếp.',
    gmapsUrl: null,
  },
  {
    id: 77,
    name: 'Cá diêu hồng hấp gừng hành',
    description: 'Cá hấp nóng hổi, thịt cá mềm ngọt, dậy mùi thơm của hành lá, gừng, thì là. Món này cuốn bánh tráng cùng bún, rau sống chấm nước mắm chua ngọt rất ngon.',
    imageUrl: getPlaceholderImage('ca_dieu_hong_hap_gung_hanh.jpg'),
    imageHint: 'steamed fish ginger',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Sốt: dầu hào, tương, đường, hạt nêm, tiêu khuấy tan.Ướp: thoa sốt ngoài trong cá + hành khô gừng; bọc mát ít nhất 1 giờ.Hấp: nước sôi hấp cá 20-25\'; thêm hành thì là ớt sừng hấp vài phút; ăn nóng cuốn bánh tráng bún rau, chấm mắm chua ngọt.',
    gmapsUrl: null,
  },
  {
    id: 78,
    name: 'Lẩu Thái chua cay',
    description: 'Nước dùng màu đỏ cam, vị chua từ dứa, vị ngọt từ nước dừa, nước hầm xương, vị cay tê đầu lưỡi từ ớt, dậy mùi thơm của sả, lá chanh. Món lẩu này làm ấm người trong tiết trời lạnh giá.',
    imageUrl: getPlaceholderImage('lau_thai_chua_cay.jpg'),
    imageHint: 'spicy thai hotpot',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Xào: phi tỏi sả + cà chua + dầu điều + mắm nấu nhừ; trộn nước cốt dứa xay lọc rây.Nước dùng: xương chần ninh ngọt; lọc + nước dừa + cốt dứa cà; nêm lẩu Thái, mắm muối đường nêm cốt dừa sa tế tương ớt cà; thêm lá chanh, hành tây, ngô, cà múi, ớt khô.Nhúng: đun nóng nước dùng, nhúng hải sản bò rau củ.',
    gmapsUrl: null,
  },
  {
    id: 79,
    name: 'Cà ri gà',
    description: 'Thịt gà mềm ngon, khoai giữ nguyên miếng bên ngoài hơi giòn bên trong mềm mịn, nước sốt sánh màu vàng óng, vị beo béo từ cốt dừa. Đây là món bổ dưỡng, tăng cường sức khỏe trong mùa lạnh.',
    imageUrl: getPlaceholderImage('ca_ri_ga.jpg'),
    imageHint: 'chicken curry',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Gà: chà chanh muối rửa ráo chặt miếng; ướp gói cà ri, muối, đường, sa tế, nêm, tiêu, dầu điều.Chiên khoai sơ giòn.Xào: phi hành tỏi sả + gà săn.Nấu: nước/dùng ngập + ớt (tùy) lửa vừa chín; thêm khoai cà rốt hầm; cốt dừa, hành tây, nêm; ăn bánh mì/bún/cơm.',
    gmapsUrl: null,
  },
  {
    id: 80,
    name: 'Mực chiên nước mắm',
    description: 'Thịt mực dai mềm, đậm vị mặn ngọt cay. Món này ăn chơi, lai rai cùng bạn bè xem bóng đá hoặc ăn với cơm trắng đều ngon.',
    imageUrl: getPlaceholderImage('muc_chien_nuoc_mam.jpg'),
    imageHint: 'fried squid',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Sốt: 2 thìa mắm đường nước, 1 thìa tương ớt nêm tiêu khuấy.Chiên: dầu ngập + bột giòn, chiên mực giòn vàng, thấm dầu.Sốt: phi tỏi ớt + sốt sủi, trút mực đảo bám; thêm ớt sừng hành tây lá đảo đều.',
    gmapsUrl: null,
  },
  {
    id: 81,
    name: 'Cá kho su hào',
    description: 'Món ăn này tưởng lạ nhưng mùi vị rất đỗi thân quen với cá đậm vị săn chắc, su hào giòn ngọt. Món ăn này phù hợp vào thời tiết lạnh khi su hào vào độ ngon nhất.',
    imageUrl: getPlaceholderImage('ca_kho_su_hao.jpg'),
    imageHint: 'braised fish kohlrabi',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Sốt: 1.5 bát sôi + 4-5 thìa hàng mắm, 1 thìa đường, 2 thìa muối, 1 thìa nêm tiêu khuấy.Nồi đất: riềng gừng sả đáy, xen cá su hào, top riềng gừng hành su; rưới sốt xâm.Kho 2-3 lần: sôi to 10\' hớt, liu riu 1h nêm tắt nguội; lặp (thêm sôi nếu cạn); ≥3h, >8h rục; gần xong mở rưới mỡ bóng.',
    gmapsUrl: null,
  },
  {
    id: 82,
    name: 'Nem chim bồ câu',
    description: 'Món ăn này cùng với su hào xào mực, canh măng mực làm nên mâm cỗ làng gốm Bát Tràng (Hà Nội) mà nhiều người ngợi ca \'\'Ăn một miếng, nhớ cả đời\'\'.',
    imageUrl: getPlaceholderImage('nem_chim_bo_cau.jpg'),
    imageHint: 'pigeon spring rolls',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Trộn nhân: chim + lợn xay + dầu, nêm muối mắm, tiêu; thêm rau củ thái nhỏ (mộc nhĩ, cà rốt, củ đậu, miến...); trước khi gói + lòng đỏ.Gói: bánh đa nem thấm bia ẩm, múc nhân, gập gói vừa không chặt.Rán 1: dầu nóng lửa nhỏ chiên 70-80% se, thấm dầu nguội.Rán 2: lửa to vàng giòn thoát dầu.',
    gmapsUrl: null,
  },
  {
    id: 83,
    name: 'Nem lụi',
    description: 'Từng chiếc nem lụi bọc sả, mềm ngọt cuộn với rau sống, chuối xanh chấm nước mắm chua ngọt tạo nên một bản hòa tấu hấp dẫn.',
    imageUrl: getPlaceholderImage('nem_lui_nha_hang.jpg'),
    imageHint: 'lemongrass pork skewers',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Trộn: giò sống + thịt vai mỡ xay + tôm băm + bột hành tỏi, dầu hào, đường, dầu điều, bột năng, ớt, nêm mắm, tiêu; quết dẻo, mát 2-3h.Quấn: dầu tay, bọc thịt quanh gốc sả.Nướng: than/lò 180° 15\' + quết (mật ong, dầu hào, dầu điều), nướng 15-20\' chín bóng.Ăn: cuốn bánh tráng rau khế chuối dưa dứa bún, chấm mắm tỏi ớt chua ngọt.',
    gmapsUrl: null,
  },
  {
    id: 84,
    name: 'Bún giả cầy',
    description: 'Bún giả cầy có thịt mềm đậm vị nhưng bì vẫn còn chút giòn, nước sóng sánh vàng, dậy mùi thơm của mắm tôm, riềng mẻ. Món này ăn cùng bún rất ngon nhất là trong tiết trời lạnh.',
    imageUrl: getPlaceholderImage('bun_gia_cay.jpg'),
    imageHint: 'pork leg vermicelli',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Ướp: thịt + riềng nghệ sả giã, mẻ lọc, mắm tôm, mắm, rượu, muối, nêm; ≥1h (lạnh lâu hơn).Lửa 1: xào săn 5-7\', nước ngập sôi hạ liu riu 25-30\', tắt nguội.Lửa 2: 20-25\' sóng sánh, nêm + rau thơm (rau răm, hành lá, ngổ), tắt; ăn nóng bún.',
    gmapsUrl: null,
  },
  {
    id: 85,
    name: 'Gà rang gừng',
    description: 'Thịt gà săn đậm vị, dậy mùi thơm ấm nóng của gừng nhanh chóng xua tan cái lạnh của mùa đông.',
    imageUrl: getPlaceholderImage('ga_rang_gung_dong.jpg'),
    imageHint: 'ginger fried chicken',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Gà: sạch chặt miếng; ướp cốt gừng, mắm, muối, tiêu, nêm 10-15\'.Xào: phi hành, gừng giã + gà rang lửa lớn rút nước đảo đều.Hoàn thành: Gà săn, nêm vừa + gừng sợi tiêu đảo; rút nước vàng mỡ tắt, ăn nóng.',
    gmapsUrl: null,
  },
  {
    id: 86,
    name: 'Canh cá nấu su hào',
    description: 'Thịt cá mềm thơm, su hào ngọt, nước canh thanh nhẹ, điểm xuyết màu đỏ từ cà chua khiến ai cũng thích thú. Đây là món ăn dân dã của nhiều nơi Thái Bình, Hà Nam, Hải Phòng...',
    imageUrl: getPlaceholderImage('canh_ca_nau_su_hao.jpg'),
    imageHint: 'fish kohlrabi soup',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Cá: sạch chà muối chanh ráo; ướp gừng, hành băm, mắm, muối, nêm, tiêu 30\'.Chiên sơ cá.Xào: phi hành + cà chua, thêm su hào thái chì xào, nêm muối mắm.Nấu: Nồi su hào cà xào + nước sôi; thêm cá lửa vừa, nêm vừa; su hào mềm cá chín + hành, thì là, mùi tàu, đảo tắt; rắc tiêu ớt ăn nóng.',
    gmapsUrl: null,
  },
  {
    id: 87,
    name: 'Chè xoài',
    description: 'Chè vàng ươm, dậy mùi thơm từ xoài, quyện với nước cốt dừa béo ngậy, dừa sợi sần sật rất hấp dẫn. Một món ngon khi đang vào mùa xoài chín.',
    imageUrl: getPlaceholderImage('che_xoai_dong.jpg'),
    imageHint: 'mango sweet soup',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Xoài: gọt xay nhuyễn + 1-1.2l nước; giữ ít trang trí.Nấu: + đường, muối khuấy tan.Sánh: hòa bột năng + nước, từ từ khuấy lửa nhỏ chín kỹ.Dọn: múc bát + dừa nạo, xoài dư, nước cốt dừa.',
    gmapsUrl: null,
  },
  {
    id: 88,
    name: 'Đậu hũ tay cầm hải sản',
    description: 'Sự kết hợp giữa vị thanh mát của rau củ, nấm cùng vị ngọt mềm của đậu hũ sẽ đem lại hương vị khó quên.',
    imageUrl: getPlaceholderImage('dau_hu_tay_cam.jpg'),
    imageHint: 'seafood tofu hotpot',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Xào: đậu hũ chiên giòn ráo; cà rốt + gừng + nấm 5\'; + tỏi + đậu cô ve 5\' tắt.Tộ: phi hành lá + phi lê cá mực vàng 5\'.Nước: + nước + rượu đun đặc; thêm rau xào + cải thìa + tôm chín tới; rót bột năng khuấy sánh.Hoàn thành: + đậu hũ + nấm đông cô; đậy liu riu 10\' nêm vừa; rắc ngò ăn nóng.',
    gmapsUrl: null,
  },
  {
    id: 89,
    name: 'Trứng cá chiên lá lốt',
    description: 'Trứng cá vàng ươm, đượm vị, thoảng chút hương mộc từ lá lốt của làng quê. Đây là món ăn giàu omega 3 rất tốt cho trẻ em và phụ nữ.',
    imageUrl: getPlaceholderImage('trung_ca_chien_la_lot.jpg'),
    imageHint: 'fish roe omelette',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Trứng cá: rửa muối loãng, lột màng, dằm nát.Trộn: trứng cá + trứng gà + lá lốt thái nhỏ + mắm, nêm, tiêu, nước lọc đánh đều.Chiên: dầu nóng lửa nhỏ, dàn mẻ chiên vàng mặt lật, chín dọn ăn cơm.',
    gmapsUrl: null,
  },
  {
    id: 90,
    name: 'Cá kho dưa cải',
    description: 'Trứng cá vàng ươm, đượm vị, thoảng chút hương mộc từ lá lốt của làng quê. Đây là món ăn giàu omega 3 rất tốt cho trẻ em và phụ nữ.',
    imageUrl: getPlaceholderImage('ca_kho_dua_cai.jpg'),
    imageHint: 'braised fish pickles',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Ướp cá: nước hàng, mắm, đường, tiêu, nêm; mát ≥1h.Xếp nồi đất: riềng gừng đáy + dưa cải; xen cá + nước ướp + ba chỉ riềng gừng hành dưa.Kho 2-4 lần: sôi to + nước nóng xâm, liu riu 1h tắt nguội; lặp chêm nóng; lần cuối sánh 1/3 nêm + hàng, mỡ, lửa to cạn tắt.',
    gmapsUrl: null,
  },
  {
    id: 91,
    name: 'Chân gà sốt kiểu Thái',
    description: 'Chân gà giòn, thấm trọn vị chua cay mặn ngọt, dậy mùi thơm của sả, tắc, ớt, tỏi hòa quyện làm nên bản giao hưởng đậm đà chất Thái.',
    imageUrl: getPlaceholderImage('chan_ga_sot_thai.jpg'),
    imageHint: 'thai style chicken feet',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Sốt Thái: phi tỏi băm sả + mắm, đường, tương ớt, bột ớt + sả, ớt, gừng; lửa nhỏ khuấy sánh tắt nguội + cốt tắc.Chân gà: ngâm muối chanh; luộc gừng sả muối, ngậm đá nguội cắt móng ráo.Xếp: xen chân gà + cóc xoài + sả sợi vào lọ.Ngâm: đổ sốt trộn mát qua đêm; giữ mát 1 tuần.',
    gmapsUrl: null,
  },
  {
    id: 92,
    name: 'Bắp cải cuốn thịt',
    description: 'Bắp cải thanh ngọt, thịt đậm đà, cà chua sánh đỏ quyện lại tạo nên món ăn bổ dưỡng ngày đông.',
    imageUrl: getPlaceholderImage('bap_cai_cuon_thit.jpg'),
    imageHint: 'cabbage rolls pork',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Nhân: thịt xay + hành lá nhỏ + hành băm, mắm, nêm, tiêu, dầu trộn.Cuốn: lá trải múc nhân gập cuốn buộc hành.Nấu: hấp/chiên/nướng.Sốt: phi hành + cà chua băm, nêm mắm muối mềm.Hoàn thành: bắp cải + sốt liu riu sánh nêm vừa; rắc tiêu hành ăn cơm nóng.',
    gmapsUrl: null,
  },
  {
    id: 93,
    name: 'Bò sốt vang kiểu Hà Nội',
    description: 'Từ món ăn gốc của Pháp, người Hà Nội đã biến hóa món bò sốt vang, giúp món ăn trở nên thuần Việt và được nhiều người yêu thích.',
    imageUrl: getPlaceholderImage('bo_sot_vang_hanoi.jpg'),
    imageHint: 'hanoi beef stew',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Bò: rửa thấm khô thái bao diêm; ướp mắm, muối, nêm, tiêu, ớt bột, dầu điều, gừng tỏi băm, quế hồi thảo quả rang + vang đỏ; ≥1h.Sốt cà: phi bơ + tỏi, cà chua băm, nêm mắm muối mềm.Xào bò: bơ + bò săn.Ninh: + cà + nước ướp + nước ngập; nêm mắm muối nêm; sôi hạ liu riu ≥1h mềm sánh; vớt quế hồi thảo.',
    gmapsUrl: null,
  },
  {
    id: 94,
    name: 'Cháo trai',
    description: 'Bát cháo trai sánh mịn, thịt trai thơm ngon đậm vị, quẩy giòn tan, dậy mùi thơm của hành phi, rau răm, hành lá làm nên món đặc trưng chiều đông Hà Nội.',
    imageUrl: getPlaceholderImage('chao_trai.jpg'),
    imageHint: 'clam congee',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Luộc: nước xâm + gừng, hé miệng vớt; nguội tách thịt bỏ phân chanh rửa; lọc nước trong.Xào trai: phi hành + trai lửa lớn, mắm, nêm, tiêu, tắt để riêng.Nấu cháo: gạo nếp, tẻ rang + nước luộc trai; ninh nhừ.Hoàn thành: cháo nhừ + trai xào, nêm; ăn nóng quẩy + hành răm phi tiêu ớt.',
    gmapsUrl: null,
  },
  {
    id: 95,
    name: 'Bắp bò ngâm mắm',
    description: 'Bắp bò ngâm mắm thơm ngon, vừa sang chảnh vừa chống ngán cho bàn tiệc tại gia, phù hợp cho những mâm cơm ngày Tết.',
    imageUrl: getPlaceholderImage('bap_bo_ngam_mam.jpg'),
    imageHint: 'pickled beef shank',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Bắp bò: tươi rửa trần sôi giảm mùi.Luộc: nước + sả gừng hồi quế muối chín, vớt bọt.Ngâm: tỉ lệ 1.5 mắm : 1.5 nước : 1 dấm : 1 đường + tỏi sôi 5\' nguội.Xếp lọ: bắp + tiêu + tỏi; đổ ngập nén chặt mát 1-3 hôm.',
    gmapsUrl: null,
  },
  {
    id: 96,
    name: 'Măng xào tóp mỡ',
    description: 'Măng mềm ngon, vàng óng, tóp mỡ vẫn giữ được độ giòn, dậy mùi thơm của tỏi, hành lá rất hấp dẫn. Món này ăn cùng cơm nóng rất ngon, xua tan giá lạnh mùa đông.',
    imageUrl: getPlaceholderImage('mang_xao_top_mo.jpg'),
    imageHint: 'fried bamboo shoots',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Tóp mỡ: mỡ cắt, chiên 2 lần giòn.Măng: tước/cắt, luộc mở vung muối 2-3 lần rửa sạch.Xào: phi tỏi + mỡ lợn + măng nêm mắm muối; thấm mềm + tóp nêm đảo; + hành mùi tàu tắt; rắc tiêu ớt ăn nóng.',
    gmapsUrl: null,
  },
  {
    id: 97,
    name: 'Bún thịt xiên nướng',
    description: 'Những ngày đầu đông, hãy thử đổi vị cho gia đình bằng những xiên thịt nướng thơm nồng, kèm bún rau và nước chấm đậm đà.',
    imageUrl: getPlaceholderImage('bun_thit_nuong_nckd.jpg'),
    imageHint: 'grilled pork vermicelli',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Thịt: vai giòn/ba chỉ thái mỏng; ướp mắm, mật ong, dầu điều 2-3h.Nướng: nồi chiên không dầu 200° 10\'.Phết sốt (dầu hào, dầu, nước ướp); nướng 3-5\' xém.Nộm: cà rốt dưa thái + muối đường chanh mát 30-60\'.Chấm: nước + đường mắm + dứa đun lọc nguội + chanh; + nộm + tỏi ớt băm + tiêu.',
    gmapsUrl: null,
  },
  {
    id: 98,
    name: 'Cá kho chuối',
    description: 'Cá màu nâu sẫm chắc thịt, đậm đà ngậm tròn trịa các vị: bùi bùi của chuối, cay cay của ớt, thơm của riềng, lá gừng non làm nên bản giao hưởng đẹp trong mùa đông khi ăn cùng cơm nóng.',
    imageUrl: getPlaceholderImage('ca_kho_chuoi.jpg'),
    imageHint: 'braised fish banana',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Ướp cá: hành băm + nước hàng, mắm, đường, muối, tiêu, mì chính, chanh; mát ≥1h.Chuối: xanh gọt chì ngâm giấm/chanh chống thâm.Xếp nồi đất: riềng gừng củ cây lá non ba chỉ đáy; xen cá chuối; top ớt lá gừng vỏ hành; trút nước ướp.Kho 2-4 lần: + nước nóng ngập sôi hạ liu riu 1.5h tắt nguội; lặp chêm nóng; lần cuối cạn 1/3 nêm + hàng, mỡ, mở vung săn bóng.',
    gmapsUrl: null,
  },
  {
    id: 99,
    name: 'Bánh mì hot dog',
    description: 'Vỏ bánh mềm mịn, vàng ươm, thơm mùi bơ và vừng, xúc xích thơm ngon. Món này được các bạn nhỏ yêu thích.',
    imageUrl: getPlaceholderImage('banh_mi_hotdog.jpg'),
    imageHint: 'hot dog bun',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Trộn: sữa ấm + men, trứng, đường đánh tan + bột mì, bơ, muối; nhồi mịn dẻo.Ủ 1: bọc 1h nở đôi; xẹp nhồi chia 6 phần.Tạo hình: cán dài bằng xúc xích, cắt dọc khung cửa, miết đầu, cuộn xúc xích.Ủ 2: khay giấy nến phủ khăn 30\' nở.Nướng: quét lòng đỏ + sữa, rắc mè; lò 180°C 18-20\' vàng; thoa bơ bóng.',
    gmapsUrl: null,
  },
  {
    id: 100,
    name: 'Xôi thịt Hải Phòng',
    description: 'Thịt mềm, béo ngậy, thấm đượm gia vị mặn ngọt hài hòa, dậy mùi thơm rất riêng. Xôi căng bóng, mềm dẻo. Tất cả quyện vào làm nên món ngon mùa đông nơi đất cảng.',
    imageUrl: getPlaceholderImage('xoi_thit_haiphong.jpg'),
    imageHint: 'haiphong sticky rice',
    type: 'Nấu tại nhà',
    recipeOrAddress: 'Thịt: ba chỉ cắt, ngâm muối, thấm khô; gói bạc úp bì, phết giấm mát se; rải muối hạt bì.Nổ bì: lò 220° 25-30\' nổ.Ướp: cạo muối rửa; + đường, tương, màu, mắm, ngũ vị hương, nêm, chao, nước, hành tỏi băm; trộn 1h.Kho: lửa nhỏ 2-2.5h mềm; nêm vừa.Xôi: gạo nếp ngâm, đồ chín.Ăn: xôi + thịt kho + dưa góp.',
    gmapsUrl: null,
  },
];

export const dishFlavors: DishFlavor[] = [
  { dishId: 1, flavorId: 1 }, { dishId: 1, flavorId: 4 }, { dishId: 1, flavorId: 5 },
  { dishId: 2, flavorId: 2 }, { dishId: 2, flavorId: 7 },
  { dishId: 3, flavorId: 1 }, { dishId: 3, flavorId: 4 }, { dishId: 3, flavorId: 6 },
  { dishId: 4, flavorId: 1 }, { dishId: 4, flavorId: 4 }, { dishId: 4, flavorId: 12 },
  { dishId: 5, flavorId: 5 }, { dishId: 5, flavorId: 4 },
  { dishId: 6, flavorId: 3 }, { dishId: 6, flavorId: 7 },
  { dishId: 7, flavorId: 3 }, { dishId: 7, flavorId: 7 }, { dishId: 7, flavorId: 6 },
  { dishId: 8, flavorId: 5 }, { dishId: 8, flavorId: 7 },
  { dishId: 9, flavorId: 3 }, { dishId: 9, flavorId: 4 }, { dishId: 9, flavorId: 7 },
  { dishId: 10, flavorId: 5 }, { dishId: 10, flavorId: 7 },
  { dishId: 11, flavorId: 5 }, { dishId: 11, flavorId: 7 },
  { dishId: 12, flavorId: 1 }, { dishId: 12, flavorId: 4 }, { dishId: 12, flavorId: 12 },
  { dishId: 13, flavorId: 1 }, { dishId: 13, flavorId: 4 },
  { dishId: 14, flavorId: 1 }, { dishId: 14, flavorId: 7 },
  { dishId: 15, flavorId: 2 }, { dishId: 15, flavorId: 7 },
  { dishId: 16, flavorId: 3 }, { dishId: 16, flavorId: 6 },
  { dishId: 17, flavorId: 4 }, { dishId: 17, flavorId: 5 },
  { dishId: 18, flavorId: 5 }, { dishId: 18, flavorId: 6 }, { dishId: 18, flavorId: 1 },
  { dishId: 19, flavorId: 4 }, { dishId: 19, flavorId: 5 },
  { dishId: 20, flavorId: 5 },
  { dishId: 21, flavorId: 7 }, { dishId: 21, flavorId: 9 }, { dishId: 21, flavorId: 6 },
  { dishId: 22, flavorId: 5 }, { dishId: 22, flavorId: 7 },
  { dishId: 23, flavorId: 7 }, { dishId: 23, flavorId: 9 }, { dishId: 23, flavorId: 11 },
  { dishId: 24, flavorId: 7 }, { dishId: 24, flavorId: 5 },
  { dishId: 25, flavorId: 12 }, { dishId: 25, flavorId: 6 }, { dishId: 25, flavorId: 9 },
  { dishId: 26, flavorId: 8 }, { dishId: 26, flavorId: 6 },
  { dishId: 27, flavorId: 2 }, { dishId: 27, flavorId: 7 }, { dishId: 27, flavorId: 5 },
  { dishId: 28, flavorId: 3 }, { dishId: 28, flavorId: 4 }, { dishId: 28, flavorId: 7 },
  { dishId: 29, flavorId: 5 }, { dishId: 29, flavorId: 1 }, { dishId: 29, flavorId: 4 }, { dishId: 29, flavorId: 11 },
  { dishId: 30, flavorId: 1 }, { dishId: 30, flavorId: 5 },
  { dishId: 31, flavorId: 4 }, { dishId: 31, flavorId: 11 }, { dishId: 31, flavorId: 6 },
  { dishId: 32, flavorId: 7 }, { dishId: 32, flavorId: 6 }, { dishId: 32, flavorId: 11 },
  { dishId: 33, flavorId: 5 }, { dishId: 33, flavorId: 4 }, { dishId: 33, flavorId: 7 },
  { dishId: 34, flavorId: 1 }, { dishId: 34, flavorId: 2 }, { dishId: 34, flavorId: 4 }, { dishId: 34, flavorId: 12 },
  { dishId: 35, flavorId: 1 }, { dishId: 35, flavorId: 2 }, { dishId: 35, flavorId: 3 }, { dishId: 35, flavorId: 7 },
  { dishId: 36, flavorId: 1 }, { dishId: 36, flavorId: 4 }, { dishId: 36, flavorId: 7 },
  { dishId: 37, flavorId: 3 }, { dishId: 37, flavorId: 4 }, { dishId: 37, flavorId: 7 }, { dishId: 37, flavorId: 6 },
  { dishId: 38, flavorId: 7 }, { dishId: 38, flavorId: 2 }, { dishId: 38, flavorId: 3 },
  { dishId: 39, flavorId: 7 }, { dishId: 39, flavorId: 3 }, { dishId: 39, flavorId: 6 },
  { dishId: 40, flavorId: 6 }, { dishId: 40, flavorId: 3 }, { dishId: 40, flavorId: 1 },
  { dishId: 41, flavorId: 3 }, { dishId: 41, flavorId: 7 },
  { dishId: 42, flavorId: 1 }, { dishId: 42, flavorId: 3 }, { dishId: 42, flavorId: 7 },
  { dishId: 43, flavorId: 4 }, { dishId: 43, flavorId: 11 },
  { dishId: 44, flavorId: 3 }, { dishId: 44, flavorId: 7 }, { dishId: 44, flavorId: 12 },
  { dishId: 45, flavorId: 5 }, { dishId: 45, flavorId: 1 }, { dishId: 45, flavorId: 4 }, { dishId: 45, flavorId: 11 },
  { dishId: 46, flavorId: 3 }, { dishId: 46, flavorId: 4 }, { dishId: 46, flavorId: 7 }, { dishId: 46, flavorId: 12 },
  { dishId: 47, flavorId: 1 }, { dishId: 47, flavorId: 3 }, { dishId: 47, flavorId: 7 },
  { dishId: 48, flavorId: 5 }, { dishId: 48, flavorId: 7 }, { dishId: 48, flavorId: 4 },
  { dishId: 49, flavorId: 5 }, { dishId: 49, flavorId: 4 }, { dishId: 49, flavorId: 7 },
  { dishId: 50, flavorId: 1 }, { dishId: 50, flavorId: 2 }, { dishId: 50, flavorId: 3 }, { dishId: 50, flavorId: 12 },
  { dishId: 51, flavorId: 4 }, { dishId: 51, flavorId: 5 },
  { dishId: 52, flavorId: 1 }, { dishId: 52, flavorId: 4 }, { dishId: 52, flavorId: 5 },
  { dishId: 53, flavorId: 1 }, { dishId: 53, flavorId: 4 }, { dishId: 53, flavorId: 5 },
  { dishId: 54, flavorId: 4 }, { dishId: 54, flavorId: 5 }, { dishId: 54, flavorId: 6 }, { dishId: 54, flavorId: 13 },
  { dishId: 55, flavorId: 4 }, { dishId: 55, flavorId: 5 }, { dishId: 55, flavorId: 6 }, { dishId: 55, flavorId: 11 }, { dishId: 55, flavorId: 12 },
  { dishId: 56, flavorId: 1 }, { dishId: 56, flavorId: 4 }, { dishId: 56, flavorId: 5 },
  { dishId: 57, flavorId: 4 }, { dishId: 57, flavorId: 6 }, { dishId: 57, flavorId: 5 },
  { dishId: 58, flavorId: 4 }, { dishId: 58, flavorId: 6 }, { dishId: 58, flavorId: 5 },
  { dishId: 59, flavorId: 4 }, { dishId: 59, flavorId: 5 }, { dishId: 59, flavorId: 6 },
  { dishId: 60, flavorId: 4 }, { dishId: 60, flavorId: 5 },
  { dishId: 61, flavorId: 9 }, { dishId: 61, flavorId: 7 },
  { dishId: 62, flavorId: 1 }, { dishId: 62, flavorId: 4 },
  { dishId: 63, flavorId: 8 }, { dishId: 63, flavorId: 6 },
  { dishId: 64, flavorId: 8 }, { dishId: 64, flavorId: 6 },
  { dishId: 65, flavorId: 8 }, { dishId: 65, flavorId: 1 },
  { dishId: 66, flavorId: 7 }, { dishId: 66, flavorId: 6 },
  { dishId: 67, flavorId: 7 }, { dishId: 67, flavorId: 9 },
  { dishId: 68, flavorId: 5 }, { dishId: 68, flavorId: 7 }, { dishId: 68, flavorId: 9 },
  { dishId: 69, flavorId: 5 }, { dishId: 69, flavorId: 7 },
  { dishId: 70, flavorId: 4 }, { dishId: 70, flavorId: 6 },
  { dishId: 71, flavorId: 9 }, { dishId: 71, flavorId: 7 },
  { dishId: 72, flavorId: 3 }, { dishId: 72, flavorId: 4 }, { dishId: 72, flavorId: 12 },
  { dishId: 73, flavorId: 3 }, { dishId: 73, flavorId: 4 }, { dishId: 73, flavorId: 5 },
  { dishId: 74, flavorId: 3 }, { dishId: 74, flavorId: 11 }, { dishId: 74, flavorId: 6 },
  { dishId: 75, flavorId: 3 }, { dishId: 75, flavorId: 2 }, { dishId: 75, flavorId: 12 },
  { dishId: 76, flavorId: 3 }, { dishId: 76, flavorId: 4 }, { dishId: 76, flavorId: 1 },
  { dishId: 77, flavorId: 3 }, { dishId: 77, flavorId: 7 },
  { dishId: 78, flavorId: 8 }, { dishId: 78, flavorId: 4 },
  { dishId: 79, flavorId: 3 }, { dishId: 79, flavorId: 4 }, { dishId: 79, flavorId: 6 },
  { dishId: 80, flavorId: 9 }, { dishId: 80, flavorId: 2 },
  { dishId: 81, flavorId: 3 }, { dishId: 81, flavorId: 4 }, { dishId: 81, flavorId: 1 },
  { dishId: 82, flavorId: 3 }, { dishId: 82, flavorId: 7 },
  { dishId: 83, flavorId: 9 }, { dishId: 83, flavorId: 7 },
  { dishId: 84, flavorId: 3 }, { dishId: 84, flavorId: 7 }, { dishId: 84, flavorId: 11 },
  { dishId: 85, flavorId: 3 }, { dishId: 85, flavorId: 7 },
  { dishId: 86, flavorId: 3 }, { dishId: 86, flavorId: 4 }, { dishId: 86, flavorId: 5 },
  { dishId: 87, flavorId: 4 }, { dishId: 87, flavorId: 6 }, { dishId: 87, flavorId: 13 },
  { dishId: 88, flavorId: 3 }, { dishId: 88, flavorId: 4 }, { dishId: 88, flavorId: 5 },
  { dishId: 89, flavorId: 3 }, { dishId: 89, flavorId: 7 }, { dishId: 89, flavorId: 12 },
  { dishId: 90, flavorId: 3 }, { dishId: 90, flavorId: 1 },
  { dishId: 91, flavorId: 8 }, { dishId: 91, flavorId: 9 },
  { dishId: 92, flavorId: 3 }, { dishId: 92, flavorId: 4 }, { dishId: 92, flavorId: 5 },
  { dishId: 93, flavorId: 9 }, { dishId: 93, flavorId: 7 }, { dishId: 93, flavorId: 6 },
  { dishId: 94, flavorId: 3 }, { dishId: 94, flavorId: 4 }, { dishId: 94, flavorId: 11 },
  { dishId: 95, flavorId: 3 }, { dishId: 95, flavorId: 1 }, { dishId: 95, flavorId: 7 },
  { dishId: 96, flavorId: 3 }, { dishId: 96, flavorId: 7 }, { dishId: 96, flavorId: 12 },
  { dishId: 97, flavorId: 9 }, { dishId: 97, flavorId: 7 },
  { dishId: 98, flavorId: 3 }, { dishId: 98, flavorId: 4 }, { dishId: 98, flavorId: 11 },
  { dishId: 99, flavorId: 4 }, { dishId: 99, flavorId: 6 }, { dishId: 99, flavorId: 7 },
  { dishId: 100, flavorId: 3 }, { dishId: 100, flavorId: 4 }, { dishId: 100, flavorId: 6 },
];

export const dishIngredients: DishIngredient[] = [
  { dishId: 1, ingredientId: 11 }, { dishId: 1, ingredientId: 4 }, { dishId: 1, ingredientId: 53 },
  { dishId: 2, ingredientId: 2 }, { dishId: 2, ingredientId: 9 }, { dishId: 2, ingredientId: 8 },
  { dishId: 3, ingredientId: 14 }, { dishId: 3, ingredientId: 4 },
  { dishId: 4, ingredientId: 12 }, { dishId: 4, ingredientId: 23 },
  { dishId: 5, ingredientId: 22 }, { dishId: 5, ingredientId: 24 },
  { dishId: 6, ingredientId: 10 }, { dishId: 6, ingredientId: 3 }, { dishId: 6, ingredientId: 25 }, { dishId: 6, ingredientId: 18 },
  { dishId: 7, ingredientId: 1 }, { dishId: 7, ingredientId: 23 },
  { dishId: 8, ingredientId: 56 }, { dishId: 8, ingredientId: 14 }, { dishId: 8, ingredientId: 17 },
  { dishId: 9, ingredientId: 3 }, { dishId: 9, ingredientId: 24 },
  { dishId: 10, ingredientId: 28 }, { dishId: 10, ingredientId: 40 },
  { dishId: 11, ingredientId: 10 }, { dishId: 11, ingredientId: 2 },
  { dishId: 12, ingredientId: 2 }, { dishId: 12, ingredientId: 39 }, { dishId: 12, ingredientId: 17 },
  { dishId: 13, ingredientId: 29 }, { dishId: 13, ingredientId: 4 },
  { dishId: 14, ingredientId: 30 }, { dishId: 14, ingredientId: 32 },
  { dishId: 15, ingredientId: 33 }, { dishId: 15, ingredientId: 9 }, { dishId: 15, ingredientId: 8 },
  { dishId: 16, ingredientId: 1 }, { dishId: 16, ingredientId: 4 }, { dishId: 16, ingredientId: 23 },
  { dishId: 17, ingredientId: 35 }, { dishId: 17, ingredientId: 37 },
  { dishId: 18, ingredientId: 36 }, { dishId: 18, ingredientId: 3 }, { dishId: 18, ingredientId: 16 },
  { dishId: 19, ingredientId: 37 }, { dishId: 19, ingredientId: 35 }, { dishId: 19, ingredientId: 76 }, { dishId: 19, ingredientId: 79 },
  { dishId: 20, ingredientId: 38 }, { dishId: 20, ingredientId: 37 },
  { dishId: 21, ingredientId: 96 }, { dishId: 21, ingredientId: 14 }, { dishId: 21, ingredientId: 52 }, { dishId: 21, ingredientId: 97 }, { dishId: 21, ingredientId: 98 }, { dishId: 21, ingredientId: 99 },
  { dishId: 22, ingredientId: 5 }, { dishId: 22, ingredientId: 2 }, { dishId: 22, ingredientId: 18 }, { dishId: 22, ingredientId: 63 },
  { dishId: 23, ingredientId: 24 }, { dishId: 23, ingredientId: 9 }, { dishId: 23, ingredientId: 16 },
  { dishId: 24, ingredientId: 2 }, { dishId: 24, ingredientId: 95 },
  { dishId: 25, ingredientId: 93 }, { dishId: 25, ingredientId: 3 }, { dishId: 25, ingredientId: 24 },
  { dishId: 26, ingredientId: 5 }, { dishId: 26, ingredientId: 62 }, { dishId: 26, ingredientId: 14 },
  { dishId: 27, ingredientId: 2 }, { dishId: 27, ingredientId: 94 }, { dishId: 27, ingredientId: 60 },
  { dishId: 28, ingredientId: 11 }, { dishId: 28, ingredientId: 24 },
  { dishId: 29, ingredientId: 71 }, { dishId: 29, ingredientId: 3 }, { dishId: 29, ingredientId: 24 }, { dishId: 29, ingredientId: 5 },
  { dishId: 30, ingredientId: 12 }, { dishId: 30, ingredientId: 60 },
  { dishId: 31, ingredientId: 57 }, { dishId: 31, ingredientId: 45 },
  { dishId: 32, ingredientId: 49 }, { dishId: 32, ingredientId: 44 },
  { dishId: 33, ingredientId: 5 }, { dishId: 33, ingredientId: 13 },
  { dishId: 34, ingredientId: 91 }, { dishId: 34, ingredientId: 65 },
  { dishId: 35, ingredientId: 3 }, { dishId: 35, ingredientId: 25 }, { dishId: 35, ingredientId: 1 }, { dishId: 35, ingredientId: 9 },
  { dishId: 36, ingredientId: 2 }, { dishId: 36, ingredientId: 16 },
  { dishId: 37, ingredientId: 10 }, { dishId: 37, ingredientId: 12 },
  { dishId: 38, ingredientId: 2 }, { dishId: 38, ingredientId: 31 },
  { dishId: 39, ingredientId: 50 }, { dishId: 39, ingredientId: 24 },
  { dishId: 40, ingredientId: 66 }, { dishId: 40, ingredientId: 51 }, { dishId: 40, ingredientId: 14 },
  { dishId: 41, ingredientId: 34 }, { dishId: 41, ingredientId: 1 },
  { dishId: 42, ingredientId: 10 }, { dishId: 42, ingredientId: 1 }, { dishId: 42, ingredientId: 88 },
  { dishId: 43, ingredientId: 49 }, { dishId: 43, ingredientId: 68 },
  { dishId: 44, ingredientId: 46 }, { dishId: 44, ingredientId: 24 }, { dishId: 44, ingredientId: 101 },
  { dishId: 45, ingredientId: 71 }, { dishId: 45, ingredientId: 3 }, { dishId: 45, ingredientId: 24 }, { dishId: 45, ingredientId: 5 },
  { dishId: 46, ingredientId: 61 }, { dishId: 46, ingredientId: 1 },
  { dishId: 47, ingredientId: 69 }, { dishId: 47, ingredientId: 88 },
  { dishId: 48, ingredientId: 5 }, { dishId: 48, ingredientId: 70 },
  { dishId: 49, ingredientId: 62 }, { dishId: 49, ingredientId: 18 }, { dishId: 49, ingredientId: 21 },
  { dishId: 50, ingredientId: 71 }, { dishId: 50, ingredientId: 35 }, { dishId: 50, ingredientId: 18 }, { dishId: 50, ingredientId: 72 },
  { dishId: 51, ingredientId: 74 }, { dishId: 51, ingredientId: 86 },
  { dishId: 52, ingredientId: 77 },
  { dishId: 53, ingredientId: 78 }, { dishId: 53, ingredientId: 85 },
  { dishId: 54, ingredientId: 19 }, { dishId: 54, ingredientId: 45 },
  { dishId: 55, ingredientId: 43 }, { dishId: 55, ingredientId: 44 }, { dishId: 55, ingredientId: 45 },
  { dishId: 56, ingredientId: 74 }, { dishId: 56, ingredientId: 76 }, { dishId: 56, ingredientId: 79 }, { dishId: 56, ingredientId: 35 },
  { dishId: 57, ingredientId: 81 }, { dishId: 57, ingredientId: 45 },
  { dishId: 58, ingredientId: 81 }, { dishId: 58, ingredientId: 51 },
  { dishId: 59, ingredientId: 35 }, { dishId: 59, ingredientId: 73 }, { dishId: 59, ingredientId: 76 },
  { dishId: 60, ingredientId: 82 }, { dishId: 60, ingredientId: 85 },
  { dishId: 61, ingredientId: 5 }, { dishId: 61, ingredientId: 12 }, { dishId: 61, ingredientId: 16 },
  { dishId: 62, ingredientId: 100 }, { dishId: 62, ingredientId: 1 }, { dishId: 62, ingredientId: 16 },
  { dishId: 63, ingredientId: 5 }, { dishId: 63, ingredientId: 62 }, { dishId: 63, ingredientId: 14 },
  { dishId: 64, ingredientId: 89 }, { dishId: 64, ingredientId: 90 }, { dishId: 64, ingredientId: 1 },
  { dishId: 65, ingredientId: 5 }, { dishId: 65, ingredientId: 15 },
  { dishId: 66, ingredientId: 13 }, { dishId: 66, ingredientId: 5 },
  { dishId: 67, ingredientId: 96 }, { dishId: 67, ingredientId: 14 }, { dishId: 67, ingredientId: 52 },
  { dishId: 68, ingredientId: 6 }, { dishId: 68, ingredientId: 1 },
  { dishId: 69, ingredientId: 6 }, { dishId: 69, ingredientId: 2 },
  { dishId: 70, ingredientId: 19 },
  { dishId: 71, ingredientId: 12 }, { dishId: 71, ingredientId: 9 }, { dishId: 71, ingredientId: 40 },
  { dishId: 72, ingredientId: 25 }, { dishId: 72, ingredientId: 17 },
  { dishId: 73, ingredientId: 60 }, { dishId: 73, ingredientId: 12 },
  { dishId: 74, ingredientId: 2 }, { dishId: 74, ingredientId: 44 }, { dishId: 74, ingredientId: 14 },
  { dishId: 75, ingredientId: 63 }, { dishId: 75, ingredientId: 50 }, { dishId: 75, ingredientId: 8 },
  { dishId: 76, ingredientId: 29 }, { dishId: 76, ingredientId: 4 }, { dishId: 76, ingredientId: 31 },
  { dishId: 77, ingredientId: 29 }, { dishId: 77, ingredientId: 31 }, { dishId: 77, ingredientId: 58 },
  { dishId: 78, ingredientId: 3 }, { dishId: 78, ingredientId: 25 }, { dishId: 78, ingredientId: 53 }, { dishId: 78, ingredientId: 9 },
  { dishId: 79, ingredientId: 2 }, { dishId: 79, ingredientId: 20 }, { dishId: 79, ingredientId: 17 }, { dishId: 79, ingredientId: 45 },
  { dishId: 80, ingredientId: 25 }, { dishId: 80, ingredientId: 7 }, { dishId: 80, ingredientId: 40 },
  { dishId: 81, ingredientId: 11 }, { dishId: 81, ingredientId: 24 },
  { dishId: 82, ingredientId: 2 }, { dishId: 82, ingredientId: 21 },
  { dishId: 83, ingredientId: 63 }, { dishId: 83, ingredientId: 9 }, { dishId: 83, ingredientId: 3 },
  { dishId: 84, ingredientId: 12 }, { dishId: 84, ingredientId: 52 }, { dishId: 84, ingredientId: 9 },
  { dishId: 85, ingredientId: 2 }, { dishId: 85, ingredientId: 31 },
  { dishId: 86, ingredientId: 11 }, { dishId: 86, ingredientId: 4 },
  { dishId: 87, ingredientId: 35 }, { dishId: 87, ingredientId: 45 },
  { dishId: 88, ingredientId: 3 }, { dishId: 88, ingredientId: 25 }, { dishId: 88, ingredientId: 14 },
  { dishId: 89, ingredientId: 18 }, { dishId: 89, ingredientId: 50 },
  { dishId: 90, ingredientId: 11 }, { dishId: 90, ingredientId: 88 },
  { dishId: 91, ingredientId: 2 }, { dishId: 91, ingredientId: 35 }, { dishId: 91, ingredientId: 9 },
  { dishId: 92, ingredientId: 39 }, { dishId: 92, ingredientId: 24 },
  { dishId: 93, ingredientId: 1 }, { dishId: 93, ingredientId: 45 }, { dishId: 93, ingredientId: 4 },
  { dishId: 94, ingredientId: 15 }, { dishId: 94, ingredientId: 18 },
  { dishId: 95, ingredientId: 1 }, { dishId: 95, ingredientId: 7 },
  { dishId: 96, ingredientId: 60 }, { dishId: 96, ingredientId: 24 },
  { dishId: 97, ingredientId: 12 }, { dishId: 97, ingredientId: 9 },
  { dishId: 98, ingredientId: 11 }, { dishId: 98, ingredientId: 51 },
  { dishId: 99, ingredientId: 46 }, { dishId: 99, ingredientId: 18 },
  { dishId: 100, ingredientId: 49 }, { dishId: 100, ingredientId: 24 },
];

export const allRestaurants = [];
export const dishRestaurants = [];

    